### ISSUE TITLE
Hydra Bruteforce on Metasploitable 2

### ISSUE THREAD

**Issue by HackMeDevanSugars** [digininja/DVWA#297]
So I'm back again with another problem I tried to find a video that talked about how to setup this if you were using Metasploitable 2 but being that this is used as a whole other machine on my WiFi the proxy thing that the videos told me to do with burpsuite isn't working for me so how am I supposed to set up bruteforcing DVWA with hydra if DVWA isn't at my local host rather at another machines ip when I put my target website into hydra Im using (http://192.168.1.25/dvwa/login.php) not in parentheses of course but then Im not sure what to put in tuning because what Ive put which follows the videos on youtube about DVWA is not working the I run it and I get Invalid target definition thank you in advance.

**Comment by digininja** [comment]
No idea on hydra, I use Burp Intruder for all my web brute forcing.

**Comment by HackMeDevanSugars** [comment]
@digininja 
how would you do it then with burp because I just wanna get this done lol

**Comment by digininja** [comment]
Thought you said you were a red teamer?

**Comment by HackMeDevanSugars** [comment]
@digininja but this is a school project and I plan to be good at both because both interest me I just think and like the physical side much more but being that I do I don't have much experience blue teaming

**Comment by digininja** [comment]
There is a big difference between being a red teamer and being at school
learning about security when assuming knowledge levels.

For password guessing with Burp, Google using Intruder, there are loads of
tutorials out there for it. As this is your homework, we aren't going to
give you all the answers, you have to work for it otherwise you won't learn

**Comment by HackMeDevanSugars** [comment]
@digininja thats fair I will do so

**Comment by HackMeDevanSugars** [comment]
@digininja and I just think of myself as more of a red teamer its just more interesting than blue teaming

**Comment by digininja** [comment]
You are interested in learning offensive techniques. Red Teamer, to a lot of people, is a job title that implies a certain level of abilities. When asking for help, we need to know what level you are at to be able to give appropriate replies. Someone with red teamer as their job title would understand basic SQL and hence the reply to your other ticket about just adding things to the database and expecting you to understand hashing.
