### ISSUE TITLE
Docker file or docker-compose supports

### ISSUE THREAD

**Issue by peter279k** [digininja/DVWA#308]
As title, is it possible to add these file on this projects?

I think it can help developers to build their own container easily rather than prebuild Docker image.

If possible, I can help this issue.

**Comment by mike-bailey** [comment]
Personally I would agree to merge (ethicalhacker has final call) if you PR’d one but there is a relatively reliable one in a separate repo. I haven’t discussed this with others but we’ve had really out of scope Docker issues esp with aufs and mysql and having it under another contributor means we don’t get the issues filed against us. That said I can see it being a way I could get more involved with development here personally by helping maintain it 🤷‍♂️

**Comment by digininja** [comment]
If you are happy supporting it then I'd be ok with adding it in. See what
the owner of the other repo thinks as we would be taking traffic away from
him.
