### ISSUE TITLE
problem in command injection (LOW)

### ISSUE THREAD

**Issue by MenyBgu** [digininja/DVWA#310]
hi all, 
the security level is on low and im trying to write an address (like google.com or anything else) but it's seem like nothing happend, the page like refreshing itself (nothing happend). when i wrote things like "abc" just to see if any error occured, again nothing.
when i wrote for example "google.com & dir" it shows me the dir and working fine (with double && its not working).
any one have idea why it's working strange ?
thanks

**Comment by digininja** [comment]
For me, if I enter google.com I get this:

![image](https://user-images.githubusercontent.com/117081/61211747-4fa7ad80-a6f8-11e9-8837-29b7a149077f.png)

Single and double & work as well.

We will need a lot more information from you to help debug things. What OS, what do the web server logs say, exactly what are you entering, screenshots often help as well.
