### ISSUE TITLE
Can't get the XSS examples to work

### ISSUE THREAD

**Issue by synedra** [digininja/DVWA#312]
I have the DVWA installed on a system (http//security-labs.web.astronaut.training).

I've turned the security down to "Low".

I can't get the alerts to pop up.  I've tried Safari and Chrome.

I'm doing the basic <script>alert(document.cookie)</script>

Can anyone help me?

**Comment by digininja** [comment]
First, get that off the internet now! Otherwise you'll lose the box pretty
quickly.

If you are taking about the reflected xss lab then read up on built in xss
protections to find out why.

**Comment by digininja** [comment]
I strongly recommend you remove that box from the internet. DVWA has deliberate vulnerabilities in it, including command injection. Through it, I can potentially take full control of your server.
