### ISSUE TITLE
Security settings are not sticky

### ISSUE THREAD

**Issue by synedra** [digininja/DVWA#315]
I set the security to "Low" so I could test my hack, but when I move to the SQL injection page, the security settings revert to "Impossible".  I've tried mucking with my cookies and fiddling with the dropdown to no avail.  It is simply broken.

How can I fix this?

Kirsten

**Comment by synedra** [comment]
![image](https://user-images.githubusercontent.com/372880/64567090-4445bc80-d30c-11e9-849d-6b0b496539e4.png)

![image](https://user-images.githubusercontent.com/372880/64567143-693a2f80-d30c-11e9-837b-87847be279bc.png)

**Comment by digininja** [comment]
It's an occasional bug. You've got a page specific cookie set for that
page, clear the cookies and try again. If you can't get rid of it, use your
proxy to force the cookie to low.
