### ISSUE TITLE
Windows error  Could not connect to the MySQL service. Please check the config file.

### ISSUE THREAD

**Issue by Gimp123** [digininja/DVWA#316]
Tried everything i could think of still getting this error whenever i try to create the database. Using XAMPP to host it.

**Comment by digininja** [comment]
Detail everything you thought of and tried so we don't waste time telling
you what to try.

Also make sure you have read all the closed tickets related to this as
there is a very good chance the answer to your problem is in there.

**Comment by apolonio** [comment]
Coloque o parametro localhost em vez de 127.0.0.1
