### ISSUE TITLE
CSRF token is incorrect i suffering with the problem

### ISSUE THREAD

**Issue by Dark-Hidden-Scripter** [digininja/DVWA#322]
how to solve this problem 
csrf token issue

**Comment by digininja** [comment]
Send the correct csrf token then.

The one you send must match the one stored in the session. If you don't
have a valid session or send a pair that doesn't match then you'll get the
error.

**Comment by KaNaGaRaJJ** [comment]
how to change my csrf token .... path .....

**Comment by digininja** [comment]
Assuming you are installing DVWA to learn about web apps, your first lesson
is to learn how csrf tokens work.
