### ISSUE TITLE
DVWA不能用太高的版本吗

### ISSUE THREAD

**Issue by stone-syy** [digininja/DVWA#332]
我使用PHP-7.1.33+MySQL5.6+NGINX-1.16。
单击创建数据库时提示500错误，查看NGINXerror log：
2019/12/03 19:30:10 [error] 17986#0: *451 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /usr/local/nginx/html/dynamic/dvwa/dvwa/includes/DBMS/MySQL.php:17
Stack trace:
#0 /usr/local/nginx/html/dynamic/dvwa/setup.php(17): include_once()
#1 {main}
  thrown in /usr/local/nginx/html/dynamic/dvwa/dvwa/includes/DBMS/MySQL.php on line 17" while reading response header from upstream, client: 192.168.137.1, server: localhost, request: "POST /dvwa/setup.php HTTP/1.1", upstream: "fastcgi://192.168.137.60:9000", host: "192.168.137.60", referrer: "http://192.168.137.60/dvwa/setup.php"
2019/12/03 19:32:26 [error] 17986#0: *456 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /usr/local/nginx/html/dynamic/dvwa/dvwa/includes/DBMS/MySQL.php:17
Stack trace:
#0 /usr/local/nginx/html/dynamic/dvwa/setup.php(17): include_once()
#1 {main}
  thrown in /usr/local/nginx/html/dynamic/dvwa/dvwa/includes/DBMS/MySQL.php on line 17" while reading response header from upstream, client: 192.168.137.1, server: localhost, request: "POST /dvwa/setup.php HTTP/1.1", upstream: "fastcgi://192.168.137.60:9000", host: "192.168.137.60", referrer: "http://192.168.137.60/dvwa/setup.php"
Google了一一下这是由于PHP7更改了MySQL的链接方式导致
请问如何处理？？只能用PHP5.5及以下版本吗

**Comment by digininja** [comment]
Don't know what version of DVWA you are using, but we've not used `mysql_query` for years now.

Install the latest version instead of this one.

**Comment by stone-syy** [comment]
> 不知道您使用的是什么版本的DVWA，但是我们已经`mysql_query`有多年没有使用了。
> 
> 安装最新版本，而不是此版本。

我使用1.9版本，但是我查看了Mysql.php。确实使用mysql_connect()及mysql_query().这是怎么一回事呢
文件路径在dvwa/dvwa/includes/DBMS/MySQL.php*

**Comment by digininja** [comment]
I can't translate that, but mysql_connect and mysql_query are both very old functions which we moved away from onto mysqli_connect and mysqli_query years ago. You are using a very old version. Check out the latest code from the repo.

**Comment by digininja** [comment]
1.9 is from "5 Oct 2015". There is no way that will work any more.

**Comment by stone-syy** [comment]
> 我无法翻译，但是mysql_connect和mysql_query都是很老的函数，几年前我们就不再使用mysqli_connect和mysqli_query了。您正在使用非常旧的版本。从仓库中检出最新代码。

Thank you
