### ISSUE TITLE
i can't see any url/dvwa/*.php pages, ONLY ONE!!!

### ISSUE THREAD

**Issue by sindikto** [digininja/DVWA#342]
638/5000
Hello everyone. The problem is that firefox only shows me the setup.php page and only this one. I miss no, I don't know if maybe
the failure to install this:
apt-get -y install apache2 mysql-server php php-mysqli php-gd libapache2-mod-php
due to error:
The "mysql-server" package does not have a candidate for installation
E: The package «php-mysqli» does not have a candidate for installation .. Or maybe even
be it for the MySQL JDBC Driver for Java. Eb finally, to see if someone helped me with this.
What brings me in mind is that it shows only setup.php, it would be more reasonable if it didn't show any. Don't you think? thanks

**Comment by digininja** [comment]
What do you mean by "only shows"?

Have you completed the setup process?

What happens if you go directly to /index.php ?

If it fails when you go to the index page, what does the web server access
and error log say?

**Comment by sindikto** [comment]
- <https://translate.google.com/about/intl/en_ALL/>
   - <https://translate.google.com/community?source=web>


   - <https://www.google.com/policies>
   - <https://support.google.com/translate/>
   -
   - <http://www.google.com/about>

820/5000
1- When I say that what happens is that I write in the browser:
/ localhost / dvwa / and it loads me login.php but it is a blank page and I
am trying one yras another: --- / dvwa / index.php etc etc and none is seen
only load setup.php "only is" and if I'm going to try another folder:
--- / dvwa / vulnerabilites / view_help.php, tampokco
the sample, only blank pages.
2-setup process uf uf I just went to the config folder to rename the file
and remove the password. but as I said before you have to do some
installations that I have described before and that I have not gotten by
mistake:
The "mysql-server" package does not have a candidate for installation

3-if you put in the browser:
... / dvwa / index.php shows me how I said a blank page before, it doesn't
give any error or explanation. only shows
the web setup.php.
Enviar comentarios
Historial
Guardadas
Comunidad
<https://translate.google.es/community?source=mfooter>

**Comment by digininja** [comment]
Search for mariadb, not mysql.

**Comment by sindikto** [comment]
thanks by your time
