### ISSUE TITLE
Cannot access config.inc.php file via browser 

### ISSUE THREAD

**Issue by JobeGeo26** [digininja/DVWA#343]
Hi, I am using Nikto to scan DVWA and found this entry
![image](https://user-images.githubusercontent.com/43614365/76267554-13b2f100-6263-11ea-81c1-506f9d4f2794.png)
I am trying to follow this lesson to access the config.inc.php file using this trick on my Kali Linux environment which has apache2.4 server in which i have dvwa set up.
![image](https://user-images.githubusercontent.com/43614365/76267660-6be9f300-6263-11ea-818a-18382d909974.png)
However when i add the tilde ~ it is giving me this instead, any ideas why?
![image](https://user-images.githubusercontent.com/43614365/76267727-9b98fb00-6263-11ea-9fb5-ead67d0ac95b.png)

**Comment by digininja** [comment]
As the thing says, "some create a backup". We don't create that backup file
so you get the 404.

If you've got directory indexing enabled on that directory as Nikto
suggests, have you browsed to it to see what it does contain?
