### ISSUE TITLE
PHP function allow_url_include

### ISSUE THREAD

**Issue by Nomaan9** [digininja/DVWA#353]
I am not able setup DVWA since the past week, i have tried everything on YouTube but still it has same old problem.When i first started my DVWA page even after setting up everything it shows 'PHP function allow_url_include: Disabled' and 'PHP module gd: Missing - Only an issue if you want to play with captchas'.I have done everything changed allow_url_include to on several times but still.I have even reinstalled my Kali 3 times.

**Comment by digininja** [comment]
Do you want to play with captcha? If not, as it says, don't worry about gd.

From the top of my head, URL include is only needed if you want to do some
of the LFI labs, if you aren't bothered about those, don't worry about it.

Show the entry in the file where you set allow URL include, including the
full name of the file. Show restarting the web server and PHP after
(depending how you are running PHP).

Show the output from the phpinfo script that shows the value of allow URL
include and the name of the PHP config file in use.
