### ISSUE TITLE
File upload "Your image was not uploaded." - Securtity LOW

### ISSUE THREAD

**Issue by Gohanckz** [digininja/DVWA#354]
Hello,
I am trying to upload a .jpg image with the security level low. when trying to upload it shows me this message:

"Your image was not uploaded."

How can i solve this?

**Comment by digininja** [comment]
Check the setup page to confirm the upload directory is writable.

If it is, send a copy of the web server error logs from the time you try
the upload.

**Comment by samyukthaNaini** [comment]
/dvwa/hackable/uploads  you need to change this uploads folder permission to writeable for www-data  by going in to properties to  permissions in group select www-data

**Comment by digininja** [comment]
No response from OP.
