### ISSUE TITLE
Database error #1698

### ISSUE THREAD

**Issue by sophos1977** [digininja/DVWA#364]
Hi there, 

After a fresh installation on a virtual machine running Ubuntu Desktop, DVWA is giving to me the following error:

Could not connect to the database service.
Please check the config file.
Database Error #1698: Access denied for user 'dvwa'@'localhost'.

I´ve checked config.inc.php and database name, user name and password are correctly configured.

Please, give me a hand here.

Thanks.

**Comment by digininja** [comment]
Read the readme in GitHub, try all the debug steps in the troubleshooting
section and, if it is still broken, come back with the requested
information.

**Comment by digininja** [comment]
No response from OP
