### ISSUE TITLE
sql Database log 

### ISSUE THREAD

**Issue by Divyashivakumar10** [digininja/DVWA#365]
Hey , we can use burpsuite or ZAP to intercept the http request and response, post  sql injection, but where do i find the sql database  transaction log.
like , the log file that loads the query that has been executed and what is output of that query .
Basically a sql transaction log . where do i find it . if DVWA doesnt provide, any idea how to get that log file. I dont just want mysql error log file. i want the complete transaction log file.

**Comment by digininja** [comment]
We don't have one. Just turn on logging in mysql if you want that.
