### ISSUE TITLE
DVWA 

### ISSUE THREAD

**Issue by muhammadalifh** [digininja/DVWA#366]
hello friend, I have a problem when installing dvwa. the problem lies in:
PHP module gd: Missing - Only an issue if you want to play with captchas
PHP module mysql: Missing
PHP module pdo_mysql: Missing

can you help me?

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.4.5

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
**_PHP module gd: Missing - Only an issue if you want to play with captchas
PHP module mysql: Missing
PHP module pdo_mysql: Missing_**

MySQL username: muhammad
MySQL password: ******
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: Missing

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

[User: root] Writable folder /var/www/html/dvwa/config: Yes
Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.
allow_url_fopen = On
allow_url_include = On
These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

**Comment by digininja** [comment]
the instructions to fix this are in the readme.
