### ISSUE TITLE
DVWA - Error 

### ISSUE THREAD

**Issue by tazlai178** [digininja/DVWA#367]
I am trying to run the dvwa and got the following error

Problem 
DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

Action 
I tried to go to xampp/htdocs/dvwa/config/config.inc.php and the file name is config.inc.php but file type is still dist. how can i change the dist to php file.

**Comment by digininja** [comment]
turn on viewing file extensions in windows and you'll see the extension and be able to change it.
