### ISSUE TITLE
DVWA Command Injection issue

### ISSUE THREAD

**Issue by Abdulaziz009** [digininja/DVWA#370]
Hello everybody

I have a problem with the Command Injection command in DVWA. I tried to use the Command Injection but this problem occurred to me when I press the Command Injection tap this page appears for me.

Please help .. and Thank you.
![Screenshot_2020-07-22_11-50-18](https://user-images.githubusercontent.com/50173277/88198380-a2704b00-cc11-11ea-91b3-d5c18fa0ac38.png)

**Comment by digininja** [comment]
What page are you doing this from, what directory do you have DVWA installed into and what security level do you have set?

**Comment by Abdulaziz009** [comment]
> What page are you doing this from, what directory do you have DVWA installed into and what security level do you have set?

The directory of DVWA is /var/www/html/DVWA and the ecurity level is low.
When I press the Command Injection tap in the DVWA page, the Apache2 Debian Default Page shows up

**Comment by digininja** [comment]
I've just tested it running out of a subdirectory and it works fine. Are you on the latest Github release?

Check the action for the form related to the submit button, it should look like this:

![image](https://user-images.githubusercontent.com/117081/88201079-ef1e4b00-cc3e-11ea-995b-0e568230eebd.png)

With that, it will POST back to the same URL it came from.

**Comment by digininja** [comment]
No response from OP
