### ISSUE TITLE
I AM TRYING TO DOWNLOAD DVWA BUT IT SHOWING LIKE THIS

### ISSUE THREAD

**Issue by Likhithsai2580** [digininja/DVWA#380]
![DOUBT](https://user-images.githubusercontent.com/62712260/91826209-1bd86180-ebf2-11ea-83ac-fd56d5ad726b.png)

**Comment by digininja** [comment]
It's still working, the feature in red is only a problem if you want to use
one of the file inclusion labs. Ignore it for now.

**Comment by digininja** [comment]
No response from OP
