### ISSUE TITLE
PHP module gd: Missing

### ISSUE THREAD

**Issue by dezdorado** [digininja/DVWA#387]
PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Missing - Only an issue if you want to play with captchas
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: hack
MySQL password: ******
MySQL database: dvwa
MySQL host: 127.0.0.1

iam getting this and after restarting and in another try iam rediercting to login page and by givin "admin" and "password"
iam agin rediecting to same login page

**Comment by digininja** [comment]
As it says, gd is only required if you want to play with captchas.

Can you explain in more detail what happens when you try to log in?

Have you successfully setup the database?

**Comment by digininja** [comment]
No response, closing.

**Comment by victor1994001** [comment]
i'm having same issues, how do i solve it?

**Comment by victor1994001** [comment]
i logged into dvwa and got same 
PHP module gd: Missing - Only an issue if you want to play with captchas
how do i solve it?

**Comment by digininja** [comment]
It's in the README.
