### ISSUE TITLE
Database Error #2054

### ISSUE THREAD

**Issue by sasdallas** [digininja/DVWA#388]
Hi! I setup DVWA on a Linux Mint computer, installed php5.6 with all modules along with mysql-server.

Mysql-server did not display a config screen. I'm not sure if it should've. I have everything in the green for DVWA, but it gives me Database Error #2054: Server sent charset unknown to the client. Please, report to developers.

Thank you for your time!

**Comment by digininja** [comment]
PHP 5.x is no longer supported and I'd rather not support mysql. Upgrade to
PHP 7.x and move to Mariadb and see if that works.

If not, read the troubleshooting in the readme and submit all the details
it asks for.

**Comment by sasdallas** [comment]
Thanks, will try.

**Comment by sasdallas** [comment]
PHP7 Switched successfully. Now though, MariaDB service is failing to start and when I try to setup MySQL, it gives me unable to access using the mysqld.sock.

**Comment by digininja** [comment]
Talk to the Mariadb or Mint support people, they will be able to give you
more help than I can.

**Comment by sasdallas** [comment]
Have decided when I get home I am going to just reinstall Linux Mint. My system is absolute chaos. I now have an unremovable mysql-server-8.0 package, as dpkg stops after too many errors. So, I will try this and post again if it doesn't work. Hoping it will. Thanks for your time.

**Comment by digininja** [comment]
Ok, close this ticket then and open a new one with the new details if you
are still having problems.
