### ISSUE TITLE
DVWA login?

### ISSUE THREAD

**Issue by sasdallas** [digininja/DVWA#389]
Hey! Your answer was great! Got DVWA up and running!
Although, me, being noob to linux, don't know the login info. I tried the MYSQL login, but that did not work.
Thanks for your help!

-sasdallas

**Comment by sasdallas** [comment]
To provide a little more info, I am on the DVWA login page.
thx for your time

**Comment by digininja** [comment]
Glad it's working for you.

My suggestion, learn some Linux and how to admin the box under DVWA as well
as playing with the web app. Understanding how it works under the hood will
help understand why things work in the app as well.

**Comment by digininja** [comment]
Have a look in the readme

**Comment by sasdallas** [comment]
Hey, lol, figured it out. Checked the PHP code and spent a while looking at mysql, decided to try 'admin' and 'password' and lol it worked.

Thanks for the suggestions.
