### ISSUE TITLE
Could not connect to the database service. Please check the config file. Database Error #2002: Connection refused.

### ISSUE THREAD

**Issue by arykiller** [digininja/DVWA#391]
###  I have problem with Create/restart DataBase 

here are the version of what I'm using : 
Kali Linux 2020.3 on virtual machine 
PHP 7.4.5
mysql  Ver 15.1 
Distrib 10.3.24-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

I Solve every thing in red in the main page except for the reCAPTCHA key

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: **Disabled**
PHP function safe_mode: **Disabled**
PHP function allow_url_include: **Enabled**
PHP function allow_url_fopen: **Enabled**
PHP function magic_quotes_gpc: **Disabled**
PHP module gd: **Installed**
PHP module mysql: **Installed**
PHP module pdo_mysql: **Installed**

MySQL username: **admin**
MySQL password: *******
MySQL database: **dvwa**
MySQL host: **127.0.0.1**

reCAPTCHA key: Missing

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: **Yes**
[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: **Yes**

[User: root] Writable folder /var/www/html/dvwa/config: **Yes**
Status in red, indicate there will be an issue when trying to complete some modules.

allow_url_fopen = **On**
allow_url_include = **On**

**Comment by digininja** [comment]
My guess is that you've got the credentials for the database wrong.

Read the README, it has a troubleshooting section for all database issues. If none of those fix it for you, update the ticket with all the requested information.

**Comment by arykiller** [comment]
**yep the first error is gone now for the next** 

Could not connect to the database service.
Please check the config file.
Database Error #1698: Access denied for user 'dvwa'@'localhost'.

Couldn't find the Error 1698 in the readme file but I guess its the same as "ERROR 1045 (28000)"

but I didn't fully understand what u mean in this 
"Again, repeat the setup steps and check the database name you are using."

**Comment by digininja** [comment]
Read this section:

"Access denied" running setup

Confirm you can connect to the database on the command line using the password in the config file. If you can, and you are still getting the error, send a screenshot of you connecting on the command line and the section of the config file with the credentials in it.

**Comment by arykiller** [comment]
![2020-10-07_185513](https://user-images.githubusercontent.com/36006767/95356016-e0a30f80-08ce-11eb-9f85-164be426ffd0.png)
![2020-10-07_185531](https://user-images.githubusercontent.com/36006767/95356020-e1d43c80-08ce-11eb-9979-42de4e7d7927.png)

**Comment by digininja** [comment]
As you can see in the first screenshot, your password is wrong so the login fails. This is covered in the README which tells you to rerun the setup steps:

https://github.com/digininja/DVWA/blob/master/README.md#database-setup

If you can't connect to the database on the command line using the credentials you have, then DVWA won't be able to connect to it either.

**Comment by digininja** [comment]
And it looks like you are using an old version, it won't affect this, but grab the latest version from here if you want all the latest features.

**Comment by arykiller** [comment]
just about the password, there is a note says the the 

MySQL -u dvwa -pp@ssw0rd -D dvwa
```
*Note: There is no space after the -p*
so is this the different password u mean?
and i'll try to reinstall it on the new version

**Comment by digininja** [comment]
That means that when you provide the password on the command line you don't put a space between the -p and the password you are providing. You have done it correctly, there is no space in your screenshot. What I guess you've done wrong is something in the setup steps, you've either put a different username in, or used a different password.

The fact your first message shows the username admin, suggests that it is the username that you changed.

**Comment by digininja** [comment]
If you fix it, please remember to close this ticket.

**Comment by arykiller** [comment]
**still the same issue I'll tell u the whole process I've made till this error show** 

-  I use git clone to download the DVWA in location /var/www/html

- after this, I make sure that all the Linux package are installed and update using

`sudo apt-get -y install apache2 mariadb-server php php-mysqli php-gd libapache2-mod-php`

- I change the name of the config file from "Config.inc.php.dist" to "Config.inc.php" using 

`sudo mv Config.inc.php.dist Config.inc.php`

- Now I Start the Apache2 Service 

`sudo service apache2 start` 

on the browser search for 127.0.0.1/DVWA/setup.php

- I enable the PHP function allow_url_include 

`cd /etc/php/7.4/apache2`
`sudo nano php.ini`

and change from off to on

- For the hackable/upload, phpids_log.txt and config Changed them from no to yes using these code I didn't find in the readme how to do that so I use youtube and changed them to yes 

```
sudo cd /var/www/html/DVWA
sudo chgrp www-data /hackable/uploads
sudo chgrp www-data /external/phpids/6.0/lib/IDS/tmp/phpids_log.txt
sudo chgrp www-data /config
sudo service apache2 restart
```
I refresh the web page I have no idea what this is but it did nothing then I saw on the youtube he write another line 
```
cd /var/www/html/DVWA
sudo chmod g+w /hackable/uploads
sudo chmod g+w /external/phpids/6.0/lib/IDS/tmp/phpids_log.txt
sudo chmod g+w /config
sudo service apache2 restart
```

- now for the first issue I use the code in the README file 

```
sh
sudo service mysql start 
```
plz let me where did I get wrong with these steps if not is there another way to solve this issue and thx for your time

**Comment by digininja** [comment]
You need to do the database setup that is covered in the readme in the
section Database Setup.

**Comment by arykiller** [comment]
Do you mean this?
```
mysql> create database dvwa;
Query OK, 1 row affected (0.00 sec)

mysql> create user dvwa@localhost identified by 'p@ssw0rd';
Query OK, 0 rows affected (0.01 sec)

mysql> grant all on dvwa.* to dvwa@localhost;
Query OK, 0 rows affected (0.01 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)
```

**Comment by digininja** [comment]
Yes

**Comment by arykiller** [comment]
If you are busy or something I can wait I think it's going to take sometime 
so this is the last try I don't wanna take much longer of your time 
so I started by 
`sudo service mysql start`
then I go to the localhost 
`sudo mysql -h localhost -u root -p`
now I'm at the "MariaDB[(none)] >"
```
create database dvwa;
create user dvwa@localhost identified by 'p@ssw0rd';
grant all on dvwa.* to dvwa@localhost;
flush privileges;
```
and I got the same messages Query ok ...

now when I type 
`sudo mysql -u dvwa -pp@ssw0rd -D dvwa`
I got the ERROR 1045 and I have seen this in the readme so I follow the instructions
while I'm downloading the easiest way MariaDB 
I tried the other way 
I go to the /etc/mysql/mysql.conf.d/mysqld.cnf

`cd /etc/mysql/`
but i didnt find "mysql.conf.d" insted "mariadb.conf.d"
so i enterd the folder and looked in the files and find [mysqld] in 50-server.cnf
i open this with command 
`sudo nano 50-server.cnf`
and add default-authentication-plugin=mysql_native_password under under it 
restart mysql 
`sudo service mysql restart`

even now when I type 
`sudo mysql -u dvwa -pp@ssw0rd -D dvwa`
I got the ERROR 1045 and I have seen this in the readme so I follow the instructions

I renter MySQL using 
`sudo mysql -h localhost -u root -p`
now when I type 
`select Host, User, plugin from mysql.user where mysql.user.User = 'dvwa';`
it shows me an empty field on the plugin 
then I tried 
`ALTER USER dvwa@localhost IDENTIFIED WITH mysql_native_password BY 'p@ssw0rd';`
show me an error message 
"ERROR 1064 (42000): You have an error in your SQL syntax check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'p@ssw0rd' '

**Comment by digininja** [comment]
You have Mariadb so don't go messing with any of the database config files,
put those back to what they were when you started.

1045 is usually user doesn't exist, run those commands and get a screenshot
of them all executing successfully, then try logging in again.

**Comment by arykiller** [comment]
first-time didn't show me this error 
![2020-10-07_230642](https://user-images.githubusercontent.com/36006767/95382137-de9e7800-08f1-11eb-8d4e-ea5f296f06cc.png)

I put back database config files to what they were when you started.

**Comment by digininja** [comment]
Now try logging in on the command line with the new user. If it fails, try
with the -h localhost as well.

**Comment by arykiller** [comment]
the new user didn't work but -h localhost worked 
![2020-10-07_233341](https://user-images.githubusercontent.com/36006767/95384613-8bc6bf80-08f5-11eb-9f85-878238507626.png)

**Comment by digininja** [comment]
Try DVWA now and see.

**Comment by arykiller** [comment]
yes, it showed me the login screen now it's working thanks a lot.

**Comment by digininja** [comment]
Next time, please follow the setup instructions completely first time, they
are there for a reason.

**Comment by reaper92345** [comment]
thank you

**Comment by Bdiwy** [comment]
realy thx
