### ISSUE TITLE
Undefined index warning caused by config

### ISSUE THREAD

**Issue by Hambrook** [digininja/DVWA#393]
The default config.inc.php.dist file contains a misplaced space on [line 24](https://github.com/digininja/DVWA/blob/master/config/config.inc.php.dist#L24):

```$_DVWA[ 'db_port '] = '5432'; ```

This causes the following warning:

> Notice: Undefined index: db_port in /opt/lampp/htdocs/dvwa/dvwa/includes/dvwaPage.inc.php on line 575

**Comment by digininja** [comment]
Odd, I was sure I fixed that when I started using the port number with MariaDB, obviously I missed a commit.

Fixed now, thanks.

**Comment by Hambrook** [comment]
Happy to help.
