### ISSUE TITLE
Specific links in Instructions readme display are broken 

### ISSUE THREAD

**Issue by serkonda7** [digininja/DVWA#396]
In the readme view within DVWA's Instructions section (http://127.0.0.1/dvwa/instructions.php?doc=readme) all links that contain either `#` or `-` are broken.
Sadly I don't know PHP so I can't fix it by myself.

**Comment by digininja** [comment]
It is because the file it is trying to display is markdown not HTML or plain text, so it looks broken.

I could add a markdown renderer, but that would add either extra files to maintain or extra requirements for people to install. I'll see about pre-rendering the file and including that instead.

**Comment by serkonda7** [comment]
You mean shipping with a prebuilt file like `README.html` that will be loaded?

**Comment by digininja** [comment]
Ye. The correct way to do it would be to have a git hook that ran and
rendered the html whenever there wa a check in, but I've not got time for
that, so the easiest thing would be to do a short local script to do it and
just run it manually.

**Comment by serkonda7** [comment]
A local script still requires a local render.
As far as I can tell, https://github.com/erusev/parsedown looks quite good. Parsedown itself has no external dependencies that need to be installed. On the other hand it's close to 60kb extra size for the repo.

**Comment by digininja** [comment]
I can easily do a local render and then add it to the repo whenever I make
README changes. Then it doesn't matter what app I use to do the render.

**Comment by digininja** [comment]
Or, I could have just added a markdown to html parser!

Don't know why I didn't think of it before, just done it. Still looks a bit naff, but works better than before I think.
