### ISSUE TITLE
Your image was not uploaded

### ISSUE THREAD

**Issue by mrhydra-np** [digininja/DVWA#397]
When i try to upload anything it says your image was not uploaded. can i get a suggestion 😂

**Comment by digininja** [comment]
Try a smaller file and check directory permissions

**Comment by mrhydra-np** [comment]
I tried with 100kb file again got same error and where can i check directory permissions? Cant find it ![image](https://user-images.githubusercontent.com/73021341/96711413-62288200-1352-11eb-8dbd-0d94f04e8a24.jpeg)

**Comment by digininja** [comment]
Do some research on either Linux or Windows directory permissions. The README tells you where the directory is.

**Comment by digininja** [comment]
Any further updates before the issue is closed?

**Comment by digininja** [comment]
closing due to lack of updates.
