### ISSUE TITLE
Database Error #1045: Access denied for user 'user'@'localhost' (using password: NO).

### ISSUE THREAD

**Issue by hiteshsuthar29** [digininja/DVWA#399]
Please help me for this error 

Could not connect to the database service.
Please check the config file.
Database Error #1045: Access denied for user 'user'@'localhost' (using password: NO).

**Comment by digininja** [comment]
Read the README, work through all the troubleshooting and if it still doesn't work come back with all the requested information and screenshots.

**Comment by hiteshsuthar29** [comment]
Ok I try it

Hitesh Kumar

**Comment by digininja** [comment]
Issue gone stale, closing.
