### ISSUE TITLE
Unable to connect to the database.

### ISSUE THREAD

**Issue by chenxiaoquan233** [digininja/DVWA#400]
Env:
Mysql8 on docker
PHP 7.4
Nginx

Question:
On the setup page, when clicking the "Create / Reset Database" button, it surely starts creating database, and i can see dvwa database in mysql. But few seconds later, the page freshes automatically, saying that "Unable to connect to the database."

p.s.: I'm sure that I typed the right username, password of mysql, and I tried many methods I can find on google and old issues here, such as making the password blank, create a specific user for it... None of them makes sense.

**Comment by digininja** [comment]
Please read the readme and follow all the troubleshooting instructions and
then if still having problems reply with all the requested information.

**Comment by chenxiaoquan233** [comment]
I switched the database from MySQL to MariaDB, PHP7.4 to PHP7.0, Nginx to Apache2.2, but still met the same problem

**Comment by digininja** [comment]
Send in all the information requested in the troubleshooting section and
I'll have a look at it then.

**Comment by chenxiaoquan233** [comment]
I just fixed it.
You forgot to specify the database port in dvwa/includes/dvwaPage.inc.php at these functions:
Line 467: mysqli_connect()
Line 475: new PDO()

**Comment by digininja** [comment]
Fixed that, well spotted.
