### ISSUE TITLE
Could not connect to the database service. Please check the config file. Database Error #1045: Access denied for user 'dvwa'@'localhost' (using password: NO).

### ISSUE THREAD

**Issue by RETR0-OS** [digininja/DVWA#403]
When I am trying to create a database while signing up for DVWA on firefox , I am encountering the above mentioned error . I have tried the following methods :--
Changing '127.0.0.1' to 'localhost' and vice versa 
Changing db_password to  blank
Changing db_user to 'root'
And the port on which it is running is also 3306 
please help 
![Screenshot 2020-11-11 02_50_47](https://user-images.githubusercontent.com/74290459/98784399-0e74fa00-2421-11eb-918a-2ee9dd72b6c6.png)
![Screenshot 2020-11-11 02_51_02](https://user-images.githubusercontent.com/74290459/98784410-1339ae00-2421-11eb-8984-814de2e04905.png)

**Comment by digininja** [comment]
Read the troubleshooting section in the readme and come back with all the
information it requests if it doesn't solve your problem.

**Comment by digininja** [comment]
closing due to lack of reply
