### ISSUE TITLE
Using docker-compose for local setup

### ISSUE THREAD

**Issue by onlinejudge95** [digininja/DVWA#405]
Can I use docker for the local setup of dvwa. My main concern being would it block some of the vulnerabilities of this app, especially around any network vulnerability. If not I would be happy to raise a PR for dockerizing the project.

**Comment by digininja** [comment]
Read the readme, we already have a Docker container.

I don't use Docker so don't support it in any way, if there are any issues,
you would need to raise them with person who added it.
