### ISSUE TITLE
Can't use reverse proxy on DVWA container for WAF project

### ISSUE THREAD

**Issue by NirAlon** [digininja/DVWA#410]
Hi,

I'm using DVWA tool for testing my WAF project. 
I build a docker image for DVWA and it works perfect as a localhost, My WAF is developed on reverse proxy on python env and it should filter and block any vulnerable http request that send to DVWA localhost. 

The problem is that My reverse proxy is can't get communication with the database on the container.

With the revers proxy I can get into the login page but once I sign in with admin and password nothing happens, it render me to the login page again, Also If I go to the setup page and click on the 'create/reset DataBase' nothing happens.

Any ideas?

**Comment by digininja** [comment]
Sounds like your WAF is broken and needs fixing.

If you are looking for commercial help with development, let me know,
otherwise, I'm too busy at the moment to take on helping develop any more
projects at the moment.
