### ISSUE TITLE
Database Error #2054: Server sent charset unknown to the client

### ISSUE THREAD

**Issue by f1nl0wt3ch** [digininja/DVWA#413]
Could not connect to the database service.
Please check the config file.
Database Error #2054: Server sent charset unknown to the client. Please, report to the developers.

P.S: 2021-01-06T19:21:11.086184Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22-0ubuntu0.20.04.3'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)

**Comment by digininja** [comment]
What character set is the database using?

**Comment by f1nl0wt3ch** [comment]
I'm not sure about that, I think it should be utf-8. Where can I find it?

**Comment by f1nl0wt3ch** [comment]
@digininja 

> mysql> SELECT SCHEMA_NAME 'database', default_character_set_name 'charset', DEFAULT_COLLATION_NAME 'collation' FROM information_schema.SCHEMATA;
+--------------------+---------+--------------------+
| database           | charset | collation          |
+--------------------+---------+--------------------+
| mysql              | utf8mb4 | utf8mb4_0900_ai_ci |
| information_schema | utf8    | utf8_general_ci    |
| performance_schema | utf8mb4 | utf8mb4_0900_ai_ci |
| sys                | utf8mb4 | utf8mb4_0900_ai_ci |
| dvwa               | utf8mb4 | utf8mb4_0900_ai_ci |
+--------------------+---------+--------------------+
5 rows in set (0.00 sec)

dvwa is the database, that I'm using.

**Comment by digininja** [comment]
Try changing it to UTF8 and see if that fixes it.

**Comment by f1nl0wt3ch** [comment]
Yeah, it works. Thank a lot @digininja!

**Comment by digininja** [comment]
Good. Please close the ticket.
