### ISSUE TITLE
When the default Security Level is impossible, regardless of whether the Level is modified again, when entering the Brute Force page, the Cookie always has two Security parameters, and the first is always impossible, and the second is the currently set Level

### ISSUE THREAD

**Issue by RiotGamesU** [digininja/DVWA#415]
I found a place that seems to be a bug:

I set the security from the default Impossible to Low, but when I visit the Brute Force page, the cookie looks like this (I tested several other pages, and this did not happen):

Cookie: security=impossible; security=low; PHPSESSID = xxxxxxxxxx

This situation occurs when I use the two domain names of the local host and the initial ip address, but it does not happen when I use the domain name 127.0.0.1. By the way, when DVWA is installed, the database is initialized and the first time you log in to DVWA, The domian name I used is 127.0.0.1

I searched the issues and tried to clear the browser cookies, but the above situation happened again
Remarks: The reorganized ip address is used because my Burp Suite cannot capture the data packets of 127.0.0.1 and localhost, I am trying to solve this problem

In order to determine the problem, I tested the situation where the safety of the replacement is set to low, medium, high and impossible. When the safety of the replacement is low, medium and high, the above situation will not occur. When some When security is not possible, there are always two security parameters in the Cookie when visiting the Brute Force page, and the first one is always impossible, and the second is the security currently set. Therefore, in this case, for Brute The security level of the penetration test of the Force page is always impossible

**Comment by digininja** [comment]
It is a known issue and there have been a few tickets raised about it. Something is setting a duplicate ticket scoped at just that page so you end up with two cookies with conflicting values.

It shouldn't be too hard to track down, it is just that no one has ever been able to come up with a completely reproducible bug, it always seems to happen at random. If you can find a way to reliably reproduce it then I'll look into it.

**Comment by digininja** [comment]
Please reopen if you find a way to reproduce it
