### ISSUE TITLE
php53 error with `/vulnerabilities/sqli_blind/index.php`

### ISSUE THREAD

**Issue by xx-zhang** [digininja/DVWA#416]
**i use `php53` then meet this error. how can i fix the file `/vulnerabilities/sqli_blind/index.php` to fix for php53 env.**

```
Parse error: syntax error, unexpected '[' in /var/www/app/DVWA/vulnerabilities/sqli_blind/index.php on line 65
```
![image](https://user-images.githubusercontent.com/47806549/106867631-cc4e1280-6708-11eb-8110-9bfa6482b0ee.png)

## you can reappearance this error by this  `docker-image`  
>  --> `bylexus/apache-php53` location `/var/www/`

```bash

docker run -itd --name=dvwa -e TZ=Asia/Shanghai -P -v $(pwd):/var/www/app registry.cn-beijing.aliyuncs.com/rapid7/apache-php:php53

```

**Comment by digininja** [comment]
PHP version 5.x hit end of life a long time ago so is not supported in any way.
