### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by kuzuri-03** [digininja/DVWA#418]
Database Setup

Click on the 'Create / Reset Database' button below to create or reset your database.
If you get an error make sure you have the correct user credentials in: " . realpath( getcwd() . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR . "config.inc.php" ) . "

If the database already exists, it will be cleared and the data will be reset.
You can also use this to reset the administrator credentials (\"admin // password\") at any stage.

Setup Check
{$SERVER_NAME}

{$DVWAOS}

PHP version: " . phpversion() . "
{$phpDisplayErrors}
{$phpSafeMode}
{$phpURLInclude}
{$phpURLFopen}
{$phpMagicQuotes}
{$phpGD}
{$phpMySQL}
{$phpPDO}

Backend database: {$database_type_name}
{$MYSQL_USER}
{$MYSQL_PASS}
{$MYSQL_DB}
{$MYSQL_SERVER}
{$MYSQL_PORT}

{$DVWARecaptcha}

{$DVWAUploadsWrite}
{$DVWAPHPWrite}

{$bakWritable}
Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.

allow_url_fopen = On
allow_url_include = On

These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

" . tokenField() . "

"; dvwaHtmlEcho( $page ); ?> 

even after configuring everything  the web is loading in html format 
I have tried reinstalling the whole setup still not working 
need help !!! @digininja

**Comment by digininja** [comment]
You've not got PHP enabled.

Do some searches in the form:

```
enable PHP Ubuntu
```

With whatever distro you are using and you'll find plenty of information on
how to set it up.

**Comment by digininja** [comment]
Closing due to no response
