### ISSUE TITLE
DVWA outside box

### ISSUE THREAD

**Issue by rodrigonmelo** [digininja/DVWA#424]
Hello everyone

I have a DVWA web application running on VM and I associated an IP for this VM as 192.168.xxx.xx and the host machine is on the same VLAN,

By VPN, I have accessed it using the IP above, without any problem. However when I have  to use SQL Injection from DVWA Web application appears an error that  the "site can't be reached" instead of either an error or the attack succeeding.  Perhaps a MySql configuration?

Any idea how to resolve this issue?

![image_sitenotreached](https://user-images.githubusercontent.com/14912427/111085782-3e2b3000-84ef-11eb-8f89-b9eff4430330.png)

**Comment by digininja** [comment]
This isn't a dvwa issue it is your networking that is messed up.

**Comment by digininja** [comment]
Not a DVWA issue.
