### ISSUE TITLE
PHP function allow_url_include: Disabled

### ISSUE THREAD

**Issue by Sanjay2001verma** [digininja/DVWA#428]
i try first time to install dvwa on my kali linux.
can anyone please help me to solve these errors.
![Screenshot_20210511_205039](https://user-images.githubusercontent.com/49302943/117842722-bb63ee80-b26d-11eb-99b3-ab9be920a89c.png)

**Comment by digininja** [comment]
What have you done so far to try to fix this?

Did you read the bit at the bottom of that page that tells you how to fix two of the issues?

Have you read the README which tells you how to fix others?

**Comment by digininja** [comment]
Assuming the answer was found in the manual.
