### ISSUE TITLE
500 Internal error

### ISSUE THREAD

**Issue by mohammed21986** [digininja/DVWA#429]
Hi,

i have am trying to install DVWA on below setup.

Red Hat Enterprise Linux Server release 7.9 (Maipo) (AWS EC2 Instance)
PHP Version 5.4.16
mariaDB

getting 500 internal page error while trying to access.

**Comment by digininja** [comment]
I'm not supporting PHP version 5.x any more, but if you have a look at the
entries in your error log they might tell you something about what is
failing.

**Comment by mohammed21986** [comment]
i actually check the error logs but i am not able to find out anything there. if you could please help me to set up
![image](https://user-images.githubusercontent.com/63414880/118670558-5a5f8c00-b814-11eb-8d08-3f4efa3b016b.png)
 this last time.

**Comment by mohammed21986** [comment]
202.91.135.126 - - [18/May/2021:14:37:41 +0000] "GET /DVWA/setup.php HTTP/1.1" 200 4061 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64;x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:37:41 +0000] "GET /DVWA/dvwa/css/main.css HTTP/1.1" 304 - "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:37:41 +0000] "GET /DVWA/dvwa/js/dvwaPage.js HTTP/1.1" 304 - "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0;Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:37:41 +0000] "GET /dvwa/js/add_event_listeners.js HTTP/1.1" 404 228 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:37:41 +0000] "GET /DVWA/dvwa/images/logo.png HTTP/1.1" 304 - "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:37:41 +0000] "GET /DVWA/dvwa/images/spanner.png HTTP/1.1" 304 - "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:37:42 +0000] "GET /DVWA/favicon.ico HTTP/1.1" 200 1406 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:05 +0000] "GET /DVWA/setup.php HTTP/1.1" 200 4061 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64;x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:05 +0000] "GET /dvwa/js/add_event_listeners.js HTTP/1.1" 404 228 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:05 +0000] "GET /DVWA/favicon.ico HTTP/1.1" 200 1406 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:05 +0000] "GET /DVWA/setup.php HTTP/1.1" 200 4061 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64;x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:05 +0000] "GET /dvwa/js/add_event_listeners.js HTTP/1.1" 404 228 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:06 +0000] "GET /DVWA/favicon.ico HTTP/1.1" 200 1406 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:10 +0000] "GET /DVWA/setup.php HTTP/1.1" 200 4061 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64;x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:38:10 +0000] "GET /dvwa/js/add_event_listeners.js HTTP/1.1" 404 228 "http://34.248.173.205/DVWA/setup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
202.91.135.126 - - [18/May/2021:14:40:09 +0000] "GET /infophp.php HTTP/1.1" 200 44041 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, likeGecko) Chrome/90.0.4430.212 Safari/537.36"

**Comment by digininja** [comment]
You've posted the access log, not the error log, but looking at that setup
page you are missing most of the important modules. Did you read the readme?

**Comment by mohammed21986** [comment]
for further configuration while i am clicking on create / reset datbase then again i am getting error 500

![image](https://user-images.githubusercontent.com/63414880/118677043-8cbfb800-b819-11eb-848c-545ec7ab55a2.png)

**Comment by mohammed21986** [comment]
Thanks, looks its resolved.

**Comment by digininja** [comment]
Unless you want to play with RFI and LFI you don't need to worry about the
url parameters. I'd ignore them for now and just play with what you've got.

My guess would be because you've got duplicate entries in the config file
so off overrides on, or you didn't restart the server after setting it.

**Comment by digininja** [comment]
Assuming you either got it working or moved on without it.
