### ISSUE TITLE
error 404 , Object not found

### ISSUE THREAD

**Issue by pujaoza** [digininja/DVWA#431]
I had installed Xampp in VMWare (Kali Linux), it was working since I installed then I restarted my laptop and now when I'm trying to  open dvwa and it is showing the error 404 , Object not found. Can any one guide me to solve this issue.?? All 3 servers are on running stage and working correctly still having error while loading dvwa.

**Comment by digininja** [comment]
You are either looking in the wrong subdirectory or the wrong virtual host.
Check your web server logs config and you should be able to find what you
are currently hitting and what you are supposed to be hitting.

**Comment by digininja** [comment]
Assuming you fixed it.

**Comment by BalamiRR** [comment]
Please can you help me how to check the web server logs config. I am new in ubuntu Thank you in advance.

**Comment by digininja** [comment]
Please don't try to take over other people's closed tickets, create your own.
