### ISSUE TITLE
non such file or directory found

### ISSUE THREAD

**Issue by Ramoreleaf** [digininja/DVWA#434]
hi there, im having trouble where i cant seem to access the config.ini file to change the username and password. 
When I try to access it, it says no such file directory. when I try to use dvwa via the browser to reset the database... it gives me error 1045,.... password yes. i know its an issue with the user credentials and the password database but i have no idea how to access the config files.

kindly assist

**Comment by digininja** [comment]
It is all covered in the README, this tells you how to setup the config file:

https://github.com/digininja/DVWA#database-setup

And this tells you how to fix the 1045 error:

https://github.com/digininja/DVWA#troubleshooting

**Comment by Ramoreleaf** [comment]
thank you. it worked. 

thanks for the quick reply
