### ISSUE TITLE
Can't change Security Level from High to Medium or Low in DVWA v1.0.7 

### ISSUE THREAD

**Issue by w0lfcat** [digininja/DVWA#436]
I'm testing old version Damn Vulnerable Web Application (DVWA) v1.0.7 which is installed in Metasploitable 2.

I've solved SQL Injection low & medium level and now the setting for sqli is changed to high by default. Whenever I go to DVWA Security, change it to low/medium, and submit it, I got a confirmation saying that it has been changed to low/medium.

![image](https://user-images.githubusercontent.com/71960097/123740532-2c716b00-d8db-11eb-9a17-91ea9ce3081a.png)

However, when I go back to /dvwa/vulnerabilities/sqli/ page, Security Level is set to high.

![image](https://user-images.githubusercontent.com/71960097/123740631-5591fb80-d8db-11eb-8e44-a79a2d95afb0.png)

It seems like I can't change it anymore. However, it doesn't impact other challenges such as File Inclusion, SQL Injection (Blind), XSS.

![image](https://user-images.githubusercontent.com/71960097/123740818-9be75a80-d8db-11eb-91a7-916a5c1fa3ea.png)

Is this standard behavior in DVWA v1.0.7. Would it be possible to change sqli security level back to low/medium?

I've been clearing cookies on my browser, but it didn't help. Rebooting Metasploitable 2 also didn't help.

Please let me know how to fix this as I would like to try another tricks on low/medium level.

**Comment by digininja** [comment]
Sorry, only the latest head release from GitHub is supported. Either
upgrade to that or ask the Metasploitable developers.

What I would suggest though is to look at what cookies you've got set as
they determine the security level.

**Comment by w0lfcat** [comment]
> Sorry, only the latest head release from GitHub is supported. Either upgrade to that or ask the Metasploitable developers. What I would suggest though is to look at what cookies you've got set as they determine the security level.

I'm not sure what is going on here. I saved the VM (did not shut it down), turn it on and check the cookie value in Burp.

I'm not sure what is going on here. I saved the VM (did not shut it down), turn it on and check the cookie value in Burp.

**Before**
```
GET /dvwa/security.php HTTP/1.1
Cookie: security=high; PHPSESSID=
Connection: close
```

**Changing it to low from high**
```
POST /dvwa/security.php HTTP/1.1
Cookie: security=high; PHPSESSID=
Connection: close
security=low&seclev_submit=Submit
```

**Now it has changed to low**
```
GET /dvwa/security.php HTTP/1.1
Cookie: security=low; PHPSESSID=
Connection: close
```
I did nothing, but the issue has been resolved. Not sure how to replicate it. Will monitor the cookie if this happen again in the future.
```
GET /dvwa/vulnerabilities/sqli/ HTTP/1.1
Cookie: security=low; PHPSESSID=
Connection: close
```

**Comment by digininja** [comment]
It's a known bug that is fixed in the later versions. This is why only the
latest version is supported.
