### ISSUE TITLE
DVWA css not connected (i think)

### ISSUE THREAD

**Issue by Drefff-18** [digininja/DVWA#451]
guys, my dvwa webpage has no css at all it seems like its broken help!
![image](https://user-images.githubusercontent.com/87078340/134171890-173f57f9-bd1b-47db-828c-01d1aa24afcf.png)

**Comment by digininja** [comment]
Three options, ideally, run the requests through a proxy and look for requests for the CSS file and see what happens, do you get it or do you get errors.

Or, check the browser console and the network tab, do you see any requests to CSS files?

Or, check the web server logs, do they show any requests for CSS files?

**Comment by Drefff-18** [comment]
good afternoon sir uhm currently i reisntalled php and it is now displaying properly but this is the error i am encountering right now

![image](https://user-images.githubusercontent.com/87078340/134301665-369517a5-e760-4e30-9c32-c9811da7efa2.png)

**Comment by Drefff-18** [comment]
good afternooon sir, thankfully it is now working properly thank you!
