### ISSUE TITLE
DVWA LOGIN PAGE NOT COMING UP

### ISSUE THREAD

**Issue by NonnyJay** [digininja/DVWA#455]
I am using Kali Linux 2020.1, PHP 7.4 and MariaDB 10.5.12 . I have followed the instructions diligently and repeat the process several times.
Yet, the below screenshot page is all I see when I try to load the URL (http://127.0.0.1/dvwa/setup.php).

Kindly assist.
![image](https://user-images.githubusercontent.com/23694853/137733678-0822d740-d1b8-46a5-a8d2-d005418f8b4a.png)
![image](https://user-images.githubusercontent.com/23694853/137733797-f5e558dd-11fa-40b9-8c18-ae6c10610de2.png)

**Comment by digininja** [comment]
Have you got

libapache2-mod-php

Installed?

**Comment by NonnyJay** [comment]
Yes I do.
![image](https://user-images.githubusercontent.com/23694853/137775391-ae905ed9-b499-4ec1-993b-2b6d16e802a2.png)
