### ISSUE TITLE
File Inclusion (Medium)

### ISSUE THREAD

**Issue by cyhfvg** [digininja/DVWA#459]
in file `vulnerabilities/fi/source/medium.php`

```php
$file = str_replace( array( "../", "..\"" ), "", $file );
```
In this statement, does `"..\"" ` mean `"..\\"`?

I think it has the same meaning as `"../"`, but it is compatible with different systems.

**Comment by digininja** [comment]
I think you've missed something really important in the expression.

If you look at the syntax for [str_replace](https://www.php.net/str_replace), it takes either a string or an array as the search parameter, the replace parameter and the subject parameter.

```
str_replace(
    array|string $search,
    array|string $replace,
    string|array $subject,
    int &$count = null
): string|array
```

In here, we are passing in an array, a string, and then what should be a string:

```
$file = str_replace( array( "../", "..\"" ), "", $file );
```

I can break this down into:

```
$search_array = array( "../", "..\"" );
$file = str_replace( $search_array, "", $file );
```

So what this is doing is to look for either `../` or `..\"` and replace it with `""`. The idea being to try to stop you from doing directory traversal by including either Linux or Windows file paths.

I think you might have accidentally found a bug though, the second parameter looks like it should be `..\\` as that would make more sense from what I've just described. I'll have a think about it, but I will probably fix that so the statement reads:

```
$file = str_replace( array( "../", "..\\" ), "", $file );
```

**Comment by cyhfvg** [comment]
Thank you very much for your explanation.

**Comment by digininja** [comment]
I did fix the accidental bug so the replace is now trying to stop Windows
and Linux directory traversal. It doesn't work properly though and so can
be bypassed.
