### ISSUE TITLE
SQLi blind medium submit get error

### ISSUE THREAD

**Issue by inVains** [digininja/DVWA#460]
https://github.com/digininja/DVWA/blob/63d9a118239614350a0a62927b8d1e36d6685473/vulnerabilities/sqli_blind/index.php#L64
Index.php need mysql connection $GLOBALS["___mysqli_ston"], but close by vulnerabilities/sqli_blind/source/medium.php#L22

![image](https://user-images.githubusercontent.com/2282229/143759637-539817cb-20a2-46ef-8164-4cfa1d828da6.png)

**Comment by digininja** [comment]
Fixed in https://github.com/digininja/DVWA/commit/d77b50f50bb9ab0db8eccb189fdd16d4ef2c8883

Thanks

**Comment by inVains** [comment]
Oh I see :)

**Comment by digininja** [comment]
Ignore the date, the NTP on me dev box doesn't work so I only fixed it this
morning.
