### ISSUE TITLE
File inclusion

### ISSUE THREAD

**Issue by babucarr32** [digininja/DVWA#461]
Hello, am trying to do File Inclusion in DVWA, accroding to the "DVWA Security" the security level changes from high to low, but I notice that the security does not really change, by looking at the bottom left corner, and the source code. Please help. Thank you.

**Comment by digininja** [comment]
Check your cookies, it happens occasionally that two get set, one for high
and one got low. Delete the one you don't want and things should start
working.

**Comment by babucarr32** [comment]
Thank you so much.

**Comment by digininja** [comment]
No problem. Please close the issue if fixed.
