### ISSUE TITLE
CSP Bypass (Low) can't be solved with pastebin/hastebin anymore

### ISSUE THREAD

**Issue by G2ft** [digininja/DVWA#462]
Hello,
As for the [382](https://github.com/digininja/DVWA/issues/382) issue, the CSP Bypass cannot be solved with Pastebin as indicated, but also with Hastebin because this site has changed its URL (purchase by toptal).

**Comment by digininja** [comment]
Do you have an update that will still work?

**Comment by digininja** [comment]
Should be fixed now if you want to test it.

**Comment by G2ft** [comment]
> Should be fixed now if you want to test it.

Unfortunately I don't think such a site exists and stands the test of time.
The toptal site works. Thank you!
![image](https://user-images.githubusercontent.com/97089196/148040507-c7487db0-4092-4981-adbe-2547f8128499.png)

![image](https://user-images.githubusercontent.com/97089196/148040491-575917c6-d24e-4668-a05e-4b5ec3f1afcb.png)

**Comment by digininja** [comment]
As long as it works for now, we can play catch up again next time it changes.
