### ISSUE TITLE
Captcha error connection timed out

### ISSUE THREAD

**Issue by xerox-dev** [digininja/DVWA#463]
Hi,

I install the new version of DVWA on my Kali linux with all features and I disable the firewall.

This is my configuration:

Web Server SERVER_NAME: localhost

Operating system: *nix

PHP version: 7.4.26
PHP function display_errors: Enabled (Easy Mode!)
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Installed

Backend database: MySQL/MariaDB
Database username: user
Database password: ******
Database database: dvwa
Database host: 127.0.0.1
Database port: 3306

reCAPTCHA key: ********************************************

[User: root] Writable folder /var/www/html/DVWA/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/DVWA/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

[User: root] Writable folder /var/www/html/DVWA/config: Yes

But when I try the captcha the app return me a connection timed out but the capthca is showing perfectly.
What is the possible mistake I make ?

And sorry for my English ...

**Comment by digininja** [comment]
You fixed that quickly!

**Comment by xerox-dev** [comment]
Yeah I think, I am too tired for this !

**Comment by digininja** [comment]
Things always work better after a good sleep.
