### ISSUE TITLE
problem database system connection problem #498 to fix

### ISSUE THREAD

**Issue by simu678** [digininja/DVWA#464]
498 line found 
		if( !@($GLOBALS["___mysqli_ston"] = mysqli_connect( $_DVWA[ 'db_server' ],  $_DVWA[ 'db_user' ],  $_DVWA[ 'db_password' ], "", $_DVWA[ 'db_port' ] ))

**solve the connection**
$_DVWA[ 'db_server' ] = 'localhost'; $_DVWA[ 'db_database' ] = 'dvwa'; $_DVWA[ 'db_user' ] = 'root';  $_DVWA[ 'db_password' ] = 'p@ssw0rd';

**Comment by digininja** [comment]
Either give some useful context to this or I'm closing it.
