### ISSUE TITLE
Dvwa error

### ISSUE THREAD

**Issue by harjitsingh7** [digininja/DVWA#468]
What is solution
![Uploading Screenshot_2022-02-10-16-00-40-295_com.android.chrome.jpg…]()

**Comment by digininja** [comment]
The screenshot seems to be broken so I can't see what is wrong.

Please give a full description of the issue, what you have done to try to fix it, and confirm you have read through all the README and tried all the suggested solutions in there.

**Comment by digininja** [comment]
Assuming user error and closing.

**Comment by harjitsingh7** [comment]
Screenshot

**Comment by harjitsingh7** [comment]
When click on create/reset database then "An error occured: SimpleXML not
loaded." Page come

**Comment by digininja** [comment]
All you've submitted is the word screenshot. You need to make sure you can
actually see an image after you've submitted it otherwise there is nothing
for anyone to see.

Can you send any web server error log entries that are created at the time
the error happens.

**Comment by harjitsingh7** [comment]
[Tue Feb 15 07:40:12.709795 2022] [php7:error] [pid 24913] [client
::1:40004] PHP Fatal error:  Uncaught Error: Call to undefined function
mysqli_connect() in
/var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:498\nStack trace:\n#0
/var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown
in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 498, referer:
http://localhost:8800/

**Comment by digininja** [comment]
You are missing the mysql libraries, please follow the instructions in the
readme on how to install the app correctly.

**Comment by harjitsingh7** [comment]
*Fatal error*: Uncaught Error: Call to undefined function mysqli_connect()
in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:13 Stack trace: #0
/var/www/html/dvwa/setup.php(23): include_once() #1 {main} thrown in
*/var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php* on line *13*

**Comment by digininja** [comment]
You do not have the PHP mysqli module installed, follow the install
instructions in the readme, watch out for any errors while doing it, and
they will get you a working system.
