### ISSUE TITLE
SQL Injection - undefined variable

### ISSUE THREAD

**Issue by Swam-pl** [digininja/DVWA#469]
I set up DVWA today and have a warning on SQL Injection tab. The text of the warning is the following: 
`Warning: Undefined variable $WarningHtml in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\sqli\index.php on line 40`

I'm using Windows 10. DVWA is hosted on XAMPP.

**Comment by digininja** [comment]
Fixed in commit https://github.com/digininja/DVWA/commit/294682e72f589ab3d8205a0f15c5e1e92fd26968

Thanks

**Comment by Swam-pl** [comment]
Thank you!
