### ISSUE TITLE
PHPIDS Log cleaning error

### ISSUE THREAD

**Issue by Swam-pl** [digininja/DVWA#470]
When I press "Clear Log" button in PHPIDS Log I get the following error: 

`Fatal error: Uncaught Error: Undefined constant "w" in E:\xamp\xampp_\htdocs\dvwa\dvwa\includes\dvwaPhpIds.inc.php:44 Stack trace: #0 E:\xamp\xampp_\htdocs\dvwa\ids_log.php(27): dvwaClearIdsLog() #1 {main} thrown in E:\xamp\xampp_\htdocs\dvwa\dvwa\includes\dvwaPhpIds.inc.php on line 44`

**Comment by digininja** [comment]
Fixed in https://github.com/digininja/DVWA/commit/121fca6d6e6830a2f6585098799231f58813c008

Thanks again.

**Comment by Swam-pl** [comment]
No problem. Also thanks.
