### ISSUE TITLE
Blind SQL Injection error

### ISSUE THREAD

**Issue by Swam-pl** [digininja/DVWA#471]
When I enter `54'; SELECT * FROM information_schema.tables` in Blind SQL Injection page and then press the Submit button I get the following error:
`Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\sqli_blind\source\low.php:15 Stack trace: #0 E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\sqli_blind\source\low.php(15): mysqli_num_rows(false) #1 E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\sqli_blind\index.php(34): require_once('E:\\xamp\\xampp_\\...') #2 {main} thrown in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\sqli_blind\source\low.php on line 15`

**Comment by digininja** [comment]
fixed in https://github.com/digininja/DVWA/commit/9f04ad79470de38ed5cc186aa4d1bba8d513c233

**Comment by Swam-pl** [comment]
Thank you!
