### ISSUE TITLE
GD mdule not found DVWA

### ISSUE THREAD

**Issue by zambubu** [digininja/DVWA#472]
PLEASE HELP
i have tried the following:
- checked my source.list 
- tried the apt-get install php7.4-gd
- made changes to php.ini file to enable gd2
- BUT STILL no effect. The error Still persists
- no module gd found

**Comment by digininja** [comment]
Do you want to do the one captcha module that requires gd?

**Comment by zambubu** [comment]
wanted to test for image upload vulnerabilities. without GD, DVWA wont let me upload pictures to test successfully

**Comment by digininja** [comment]
What version of PHP are you using?

I just tested this on a fresh install and it installed the right package.

```
apt install php-gd
```

**Comment by digininja** [comment]
No response - closing.
