### ISSUE TITLE
Warnings in view_help.php

### ISSUE THREAD

**Issue by Swam-pl** [digininja/DVWA#474]
After opening view_help.php I got the following warnings:
`Warning: Undefined array key "id" in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\view_help.php on line 11`
`Warning: Undefined array key "security" in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\view_help.php on line 12`
`Warning: Undefined array key "locale" in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\view_help.php on line 13`
`Warning: file_get_contents(../vulnerabilities//help/help..php): Failed to open stream: No such file or directory in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\view_help.php on line 19`

**Comment by digininja** [comment]
That page wasn't designed to be accessed directly, but fixed this in https://github.com/digininja/DVWA/commit/155210012c60186502ecb9c435060ef2942d8e72
