### ISSUE TITLE
Warnings in view_source.php

### ISSUE THREAD

**Issue by Swam-pl** [digininja/DVWA#475]
After opening view_source.php I got the following warnings:
`Warning: Undefined array key "id" in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\view_source.php on line 11`

`Warning: Undefined array key "security" in E:\xamp\xampp_\htdocs\dvwa\vulnerabilities\view_source.php on line 12`

**Comment by digininja** [comment]
Fixed in https://github.com/digininja/DVWA/commit/417e5a868745c9a8cab17345e20e602732b5cb31
