### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alexodiah** [digininja/DVWA#479]
I keep getting this error. Please explain why?:

Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' (using password: YES) in C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php:498 Stack trace: #0 C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php(498): mysqli_connect('127.0.0.1', 'dvwa', 'password', '', '3306') #1 C:\xampp\htdocs\DVWA\login.php(8): dvwaDatabaseConnect() #2 {main} thrown in C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php on line 498

**Comment by digininja** [comment]
Read the readme.
