### ISSUE TITLE
DWVA webpage

### ISSUE THREAD

**Issue by Seng0602** [digininja/DVWA#492]
Hello, first of all i am totally new to kali linux. i watched a guide video about setting up the dvwa and when i typed the url for the dvwa website page. This what i got 
![image](https://user-images.githubusercontent.com/105764290/168948339-dcc505f2-045d-41ce-9828-aeb9fa37151c.png)
any idea on how to fix this ? any help would be greatly appreciated :)

**Comment by digininja** [comment]
Closing due to no feedback.
