### ISSUE TITLE
Windows 10/MariaDB trouble with DVWA

### ISSUE THREAD

**Issue by Ellexusss** [digininja/DVWA#493]
I have tried looking at videos and tutorials on how to fix my DVWA. I can't seem to find anyone who has had this problem or a solution to it. XAMPP is installed properly, Apache and MySQL services are running. I can get to the setup page, but when i click the "Create/Reset Database" button at the bottom, I am taken to a blank white page with the following error:

Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' (using password: YES) in C:\xampp\htdocs\dvwa\dvwa\includes\DBMS\MySQL.php:13 Stack trace: #0 C:\xampp\htdocs\dvwa\dvwa\includes\DBMS\MySQL.php(13): mysqli_connect('127.0.0.1', 'dvwa', 'p@ssw0rd', '', '3306') #1 C:\xampp\htdocs\dvwa\setup.php(23): include_once('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\dvwa\dvwa\includes\DBMS\MySQL.php on line 13

Any help would be much appreciated! Thanks!
EDIT: to fill in details outlined by digininja
Windows Version:  Enterprise  64-bit
XAMPP Version: 8.1.6
(XAMPP) Control Panel Version: 3.3.0  [ Compiled: Apr 6th 2021 ]
I have read the readme.md
I have watched and originally followed the youtube video featured in the readme
folder perms have been set according to the readme
recaptcha has been generated

when running
```
>C:\xampp\mysql\bin\mysql.exe
```
I get the following error immediately
ERROR 1045 (28000): Access denied for user 'Xachrei'@'localhost' (using password: NO)

**Comment by digininja** [comment]
Please read the readme file.

**Comment by Ellexusss** [comment]
I had trouble getting into MariaDB and creating the dvwa user. Sorry for the bother, I believe it works now.
