### ISSUE TITLE
SQL injection on low security only shows blank page

### ISSUE THREAD

**Issue by KaliYoyo** [digininja/DVWA#495]
I read about the .htaccess file in the readme, but cannot find this particular .htaccess file anywhere and I'm not sure this is the solution.  Typing in the number 1 will show users on low security, but that's the only injection that will work.  For example, typing in a single quote will show a blank page, same with a colon, etc.
Typing in other in sql injections just refreshes the page.  All on low security.

I've searched online for weeks and can't find a solution, or the .htaccess file in question. 

I'm using I'm using Mysql Ver 15.1 Distrib 10.6.7-MariaDB and apache 2. PHP version 8.1.2.

Please let me know if there's a solution.  If the problem is the .htaccess file, what directory do I find it in or create it in?  The readme doesn't mention that info.

Thanks

**Comment by digininja** [comment]
As already discussed on the Hak5 forum, the .htaccess entry was nothing to do with it as it was PHP 5.x only, I've now removed it from the README.

If you want support, pick the Hak5 forum or here, I'm not bouncing messages between the two.

**Comment by digininja** [comment]
Closing due to no feedback.

**Comment by mohankk1297** [comment]
Is there any solution to this . Even I am facing same @digininja

**Comment by digininja** [comment]
This is a closed ticket. Open a new one with all the details requested in
the template.
