### ISSUE TITLE
docker run --rm -it -p 80:80 vulnerables/web-dvwa

### ISSUE THREAD

**Issue by WdehFsociety** [digininja/DVWA#496]
**Describe the bug**
During installation process, like the following, new podman option interferes with the running of the application. 

**To Reproduce**
1.Go to, /var/www/html directory 1st
Then,
git clone https://github.com/digininja/DVWA.git

apt-get -y install apache2 mariadb-server php php-mysqli php-gd libapache2-mod-php

2.Install Docker

apt install docker.io -y
apt install podman-docker -y

3.
docker pull vulnerables/web-dvwa

4.
docker run --rm -it -p 80:80 vulnerables/web-dvwa

**Logs**
Access log... 5 last lines
127.0.0.1 - - [01/Jun/2022:14:00:46 -0400] "GET /favicon.ico HTTP/1.1" 404 487 "http://127.0.0.1/login.php" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
127.0.0.1 - - [01/Jun/2022:14:03:21 -0400] "GET /login.php HTTP/1.1" 404 488 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"

Error log... 5 las lines
35906] script '/var/www/html/login.php' not found or unable to stat
[Wed Jun 01 14:03:21.269974 2022] [php:error] [pid 243175] [client 127.0.0.1:35908] script '/var/www/html/login.php' not found or unable to stat
[Wed Jun 01 14:45:14.309519 2022] [mpm_prefork:notice] [pid 177833] AH00170: caught SIGWINCH, shutting down gracefully

**Expected behaviour**
To login and use DVWA as usual... before it was so simple.

**What have you done to help fix the issue yourself?**
Checked, tried every single repository on Git and is not letting to. 

**Screenshots**

**System (please complete the following information):**
 - Description:    Kali GNU/Linux Rolling
Release:        2022.2
Codename:       kali-rolling

 - Database and Version [mysql  Ver 15.1 Distrib 10.6.7-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper]
 - PHP Version [HP 8.1.5 (cli) (built: Apr 21 2022 09:51:30) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies]
- Installed PHP modules
[0] => Core
    [1] => date
    [2] => libxml
    [3] => openssl
    [4] => pcre
    [5] => zlib
    [6] => filter
    [7] => hash
    [8] => json
    [9] => pcntl
    [10] => Reflection
    [11] => SPL
    [12] => session
    [13] => standard
    [14] => sodium
    [15] => mysqlnd
    [16] => PDO
    [17] => calendar
    [18] => ctype
    [19] => exif
    [20] => FFI
    [21] => fileinfo
    [22] => ftp
    [23] => gd
    [24] => gettext
    [25] => iconv
    [26] => mysqli
    [27] => pdo_mysql
    [28] => pdo_sqlite
    [29] => Phar
    [30] => posix
    [31] => readline
    [32] => shmop
    [33] => sockets
    [34] => sqlite3
    [35] => sysvmsg
    [36] => sysvsem
    [37] => sysvshm
    [38] => tokenizer
    [39] => Zend OPcache

**Additional context**
Got dam it!!! let fix this S**t

**Comment by digininja** [comment]
Sorry, no support for Docker, you need to talk to @thegrims or @opsxcq about that.

It looks like @opsxcq hasn't touched it in years.

https://github.com/opsxcq/docker-vulnerable-dvwa
