### ISSUE TITLE
Hi guys, i am still new to DVWA. I have a problem can you check it?

### ISSUE THREAD

**Issue by Hafzan-250601** [digininja/DVWA#499]
![Capture](https://user-images.githubusercontent.com/54774679/174751747-b2480bf2-90e8-40e3-8956-14a8a524f011.PNG)
 I m installing DVWA on Windows,I have read the solution its only for Linux. help me please

**Comment by digininja** [comment]
Do you want to play with captchas at this point in time?

**Comment by digininja** [comment]
Closing due to no feedback.
