### ISSUE TITLE
cannot upload php file onto upload vulnerability

### ISSUE THREAD

**Issue by hojn** [digininja/DVWA#5]
I have done everything seen in guides and everytime (even on low security), it dosn't upload the file.

**Comment by glaudsonml** [comment]
Check the limit of input file size in HTTP Upload form:

<input type="hidden" name="MAX_FILE_SIZE" value="100000" />

Change this or remove this line.

Best Regards.

**Comment by starkthakur** [comment]
> I have done everything seen in guides and everytime (even on low security), it dosn't upload the file.

its folder permission issue all you need is to validate what access you have , If its not appropriate modify it by access the file and then test. In my test case shown below i was not able to perform a LFI IN dvwa app and was getting the below error:
![image](https://user-images.githubusercontent.com/49287268/87354280-ee6d2100-c57b-11ea-8dc1-4cd38334141c.png)

Then i logged in to the remote server file and changed its permission level to perform the task post validating a file /etc/passwd which i was able to read.
![image](https://user-images.githubusercontent.com/49287268/87354466-33915300-c57c-11ea-9426-473db017124d.png)
After validating  I compared the file permission and modified it accordingly and was able to access it.

![image](https://user-images.githubusercontent.com/49287268/87354716-a7336000-c57c-11ea-96bd-7e7b8d3c564d.png)

**Comment by starkthakur** [comment]
> > I have done everything seen in guides and everytime (even on low security), it dosn't upload the file.
> 
> its folder permission issue all you need is to validate what access you have , If its not appropriate modify it by accessing the file permission and then test. In my test case shown below i was not able to perform a LFI in dvwa app and was getting the below error:
> ![image](https://user-images.githubusercontent.com/49287268/87354280-ee6d2100-c57b-11ea-8dc1-4cd38334141c.png)
> 
> Then i logged in to the remote server file and changed its permission level to perform the task post validating a file /etc/passwd which i was able to read.
> ![image](https://user-images.githubusercontent.com/49287268/87354466-33915300-c57c-11ea-9426-473db017124d.png)
> After validating I compared the file permission and modified it accordingly and was able to access it.
> 
> ![image](https://user-images.githubusercontent.com/49287268/87354716-a7336000-c57c-11ea-96bd-7e7b8d3c564d.png)

**Comment by ergisgjergji** [comment]
@starkthakur I had this same issue today and i found the solution just by debugging the actual php code that handles the file upload. Just do the following 2 steps like below and it will work 😄 
<img width="480" alt="Step 1" src="https://user-images.githubusercontent.com/59146973/87853437-51f3a780-c90a-11ea-9c0e-8cf32d519657.png">
<img width="482" alt="Step 2" src="https://user-images.githubusercontent.com/59146973/87853440-55872e80-c90a-11ea-8ff6-d6e5a065e06d.png">

**Comment by digininja** [comment]
Not sure if this is designed to be trolling or not, but all this does is
force the site into low security mode rather than whatever mode you are
supposed to be in.

**Comment by ergisgjergji** [comment]
@digininja The site's purpose is about testing, isn't it? And since the issue was about not being able to upload files like .php etc, that's the solution above. I am just doing a course about pen-testing, and wasnt being able to upload a shell.php file like the guy in the video, so i debugged it and found the solution.

**Comment by digininja** [comment]
Yes, you found a solution and I applaud the way you did it, but in most
tests you don't get to modify the site source so this style of attack
wouldn't work. If you could modify the source, just put your shell code
straight into that page.

**Comment by ergisgjergji** [comment]
I doubt that nowadays there are any sites that just let file uploads loose (meaning they don't perform any validation on the file extension being uploaded), since I am a developer myself.
But setting the Dvwa file upload loose I just want to simulate a vulnerable site, that's all.
Anyway, thank you for your concern.

**Comment by digininja** [comment]
Why didn't you just set the level to low using the built in feature to do
that?

And I tested a site last month where I had arbitrary file upload that gave
me full shell on the box.

**Comment by ergisgjergji** [comment]
I have only started working with Dvwa today for the first time, didn't know there's a built-in feature 😝
 
And about that, well, seems there will always be a few of them.
