### ISSUE TITLE
Unable to get login page of dvwa

### ISSUE THREAD

**Issue by akshatagarwal20BCI0141** [digininja/DVWA#500]
After entering localhost/dvwa in Kali linux this error pops up always 

Fatal error: Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:498 Stack trace: #0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect() #1 {main} thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 498

I have done installation with latest version

**Comment by digininja** [comment]
Please open a report filling in the correct template and giving all the requested information.
