### ISSUE TITLE
Cannot access DVWA from external network

### ISSUE THREAD

**Issue by mysteriousx97** [digininja/DVWA#502]
Hello there, I am facing a problem which I could not access DVWA from my external network. Do you have any ideas how can I do that? I have found a solution from internet but I cannot find any .htaccess file here. It would be great if anyone could tell me any useful information.

**Comment by digininja** [comment]
Unless you really know what you are doing, you don't want to expose DVWA to the world, you'll get your box owned very quickly if you do.

**Comment by mysteriousx97** [comment]
What if I select a specific IP-Address to reveal?

**Comment by digininja** [comment]
What do you mean?

**Comment by mysteriousx97** [comment]
I am sorry. I have confused you. I want to change the access local IP-Address into some public IP-Address. So I can access from external network.

**Comment by digininja** [comment]
You really don't want to do that, if you make it accessible to the world,
someone will end up owning your box.

If you are really set on it, you need to look at how modem and look for
port forwarding.

**Comment by mysteriousx97** [comment]
I know what you are concerning. It will definitely within the firewall. 

But how can I share DVWA with my own pc? I want to access it from my own PC and the DVWA is on another OS.

**Comment by digininja** [comment]
Are you really talking about externally accessible or have you installed it
in a virtual machine and want that visible to the rest of your network?

Two very different things.

**Comment by mysteriousx97** [comment]
I have installed DVWA on my raspberry pi and I want it to be accessible from virtual machine(which is in my own pc). Which I do not want to open dvwa on my raspberry, but on my virtual machine. Two different ips.

**Comment by digininja** [comment]
Context is everything, reading that is completely different to reading what
you first asked.

The answer all depends on how you've got your network set up and how the
networking on the VM is configured. I'd need a lot more information to give
advice.

**Comment by mysteriousx97** [comment]
Well. Thank you for all the explanation. I have finally figured it out how to solve what I want. Thank you a lot.

**Comment by digininja** [comment]
You don't want to make DVWA externally accessible unless you really know
what you are doing.
