### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Jeeppler** [digininja/DVWA#504]
There are 143 commits since the release of 2.0.1 in 2020. Those are a lot of commits. Please publish a new release.

**Comment by digininja** [comment]
Why?

The only version that is supported is the current Git master branch so releases don't really mean anything.

**Comment by Jeeppler** [comment]
I got confused, because there are a few releases and afterwards nothing. You explained it why releases are not necessary, therefore this issue can be closed.
