### ISSUE TITLE
the setup page does not display correctly

### ISSUE THREAD

**Issue by Jaychoun** [digininja/DVWA#506]
Hi, I have some problems. Can you help me ?
Before that, I have read the README.MD, and I have change the file config.inc.php like this, 
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'dvwa';
$_DVWA[ 'db_password' ] = '1234';
$_DVWA[ 'db_port'] = '3307';
I sure that I have create the user 'dvwa', and  "GRANT ALL PRIVILEGES" like the README.MD.

**Describe the bug**
the webpage(127.0.0.1/dvwa-master/setup.php)  does not display correctly

**To Reproduce**
start the mysql-server, start the apache

**Logs**
[Wed Jul 13 18:51:43.642244 2022] [core:error] [pid 8524:tid 1892] (20024)The given path is misformatted or contained invalid characters: [client 127.0.0.1:1575] AH00127: Cannot map GET /%22%22 HTTP/1.1 to file, referer: http://127.0.0.1/dvwa-master/setup.php
[Wed Jul 13 19:13:48.666520 2022] [core:error] [pid 8524:tid 1900] (20024)The given path is misformatted or contained invalid characters: [client 127.0.0.1:2102] AH00127: Cannot map GET /%22%22 HTTP/1.1 to file, referer: http://127.0.0.1/dvwa-master/setup.php
[Wed Jul 13 19:17:28.500324 2022] [core:error] [pid 8524:tid 1888] (20024)The given path is misformatted or contained invalid characters: [client 127.0.0.1:2255] AH00127: Cannot map GET /%22%22 HTTP/1.1 to file, referer: http://127.0.0.1/dvwa-master/setup.php

**Screenshots**
①https://postimg.cc/PNXwNKq0  
②https://postimg.cc/sBNhMHj3

**System (please complete the following information):**
 - OS: Windows 11
 - Database and Version : 10.4.24-MariaDB
 - PHP Version : PHP 7.4.29 (cli) (built: Apr 12 2022 20:21:18) ( ZTS Visual C++ 2017 x64 )
 - Apache Version ：Server version: Apache/2.4.53 (Win64)
- Installed PHP modules: MySQLi

**Additional context**
File location：D:\xampp\htdocs\DVWA-master

**Comment by digininja** [comment]
You haven't got PHP running so the PHP scripts aren't being parse and you are getting the raw code.

**Comment by digininja** [comment]
I have no idea, DVWA sites on top of the LAMP stack so isn't something in our control.

Have you followed the instructions here?

https://www.apachefriends.org/download.html

**Comment by Jaychoun** [comment]
OK, i will  reinstall XAMPP, and try again the whole process.
