### ISSUE TITLE
setup.php# and blank login.php issue

### ISSUE THREAD

**Issue by maulikbahri** [digininja/DVWA#510]
Redirecting to 127.0.0.1/DVWA/setup.php# on kali and blank login.php page (using php8.1 apache2 mariadb)

**To Reproduce**
What have you installed, what are you running when you get the error...

Followed dijininja's steps except renaming the directory

**Expected behaviour**
Expected to go to login.php page
**What have you done to help fix the issue yourself?**
What have you tried, what research have you done, what changes have you made.

**System (please complete the following information):**
 - OS: Kali
 - Database and Version  MariaDB
 - PHP Version 8.1
- Installed PHP module All Installed(including gd)

**Comment by digininja** [comment]
What do the last few entries in the Apache error and access log file say?

When you say blank page, do you mean completely blank or just not what you
expect to see?
