### ISSUE TITLE
csp bypass(low) don't load pastebin's script 

### ISSUE THREAD

**Issue by 727489758** [digininja/DVWA#515]
result:
![图片](https://user-images.githubusercontent.com/43691462/200176126-5a6f5932-34cd-4f25-a379-07791639df28.png)
![图片](https://user-images.githubusercontent.com/43691462/200176172-53e63d22-eb8d-4efb-b8ba-419aaeed468d.png)
open developer mode load the script,but not pop-up windows.

**Comment by digininja** [comment]
Yes, that is correct functionality.

**Comment by 727489758** [comment]
Why not pop-up windows
![图片](https://user-images.githubusercontent.com/43691462/200176793-d279169f-8daa-401a-b0fe-bf6c13dcd731.png)

**Comment by digininja** [comment]
You need to review how CSP works and what restrictions stop it from working.

**Comment by 727489758** [comment]
Thanks,I will review CSP.
