### ISSUE TITLE
Fatal error: Uncaught mysqli_sql_exception

### ISSUE THREAD

**Issue by x-kx** [digininja/DVWA#521]
Fatal error: Uncaught mysqli_sql_exception: Unknown database 'dvwa' in C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php:499 Stack trace: #0 C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php(499): mysqli_query(Object(mysqli), 'USE dvwa') #1 C:\xampp\htdocs\dvwa\login.php(8): dvwaDatabaseConnect() #2 {main} thrown in C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php on line 499

Using 
Windows 11 home 
xampp 

changed config.inc.php.dist to config.inc.php
db info 
$_DVWA = array();
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = '';
$_DVWA[ 'db_port'] = '3306';

Both localhost/dvwa & 127.0.0.1  give the same error.

made sure all php libraries are installed.  
myphpadmin works fine.

**Comment by digininja** [comment]
"Unknown database 'dvwa' '

You haven't created the database.

**Comment by Umer-1337** [comment]
Create Database named "dvwa" in phpmyadmin, then try again.

**Comment by digininja** [comment]
This might help.

https://www.youtube.com/watch?v=Yzksa_WjnY0

**Comment by Jf710001011** [comment]
![image](https://user-images.githubusercontent.com/42083734/212905795-17d6de91-305f-491b-95e1-04df0910530a.png)
click here

**Comment by digininja** [comment]
Clicking that button adds the tables and data into the database, if the
database doesn't exist, which is what the error says, then the button won't
work.

**Comment by digininja** [comment]
OP gone quiet, closing
