### ISSUE TITLE
DWVA in quicks mode ?? 

### ISSUE THREAD

**Issue by Boo1251** [digininja/DVWA#524]
HI I been trying to fix this issue and took me so long to get to this point and i was wonder if there is anything i did wrong or is there a fix ??  

Thanks anyone
![Screenshot_2023-01-21_14_10_26](https://user-images.githubusercontent.com/121278875/213885374-14044e70-6055-4b09-a59e-cbdbddefd992.png)

**Comment by digininja** [comment]
Closing this, please re-open using the installation issues ticket type and provide the information requested.
