### ISSUE TITLE
Parse error in PHP versions < 5.4 caused by use of square bracket array syntax in /dvwa/dvwa/includes/dvwaPage.inc.php

### ISSUE THREAD

**Issue by deepakplay** [digininja/DVWA#529]
**Bug Description:** 
Using square brackets for arrays in the file /dvwa/dvwa/includes/dvwaPage.inc.php on line 52 causes a parse error when using PHP versions less than 5.4.

**Steps to Reproduce:**

Downgrade your PHP version to before 5.4 (I tested using version 5.2.4)
This will generate the following error: 
"_Parse error: syntax error, unexpected '[', expecting ')' in /var/www/dvwa/dvwa/includes/dvwaPage.inc.php on line 52_"

**Attempted Fix:**
Changed the square brackets to the array() syntax.

**System:**
PHP version 5.2.4
Environment: Metasploitable 2.0.0 (Ubuntu 5.10)

**Comment by digininja** [comment]
There are probably quite a few other things that won't work properly in a
seven year old version of php so not going to worry about fixing it.

DVWA is for testing app skills not really infrastructure so I recommend
installing it on a modern web stack not something so old.
