### ISSUE TITLE
I did everything but still PHP Function allow_url_include: Disabled is still disabled while installing DVWA in my virtual box in kali linux.

### ISSUE THREAD

**Issue by himz123** [digininja/DVWA#532]
I have gone through the video. 
I followed every step.
But when I installed PHP module gd, I instantly got my PHP Function allow_url_include: Disabled.
It was previously enabled but when I installed module gd, it gets automatically disabled.
![Screenshot_2023-01-30_17_31_12](https://user-images.githubusercontent.com/32019999/215538024-b8573768-8763-49ce-a908-bd14a17ad2a8.png)
![Screenshot_2023-01-30_17_31_13](https://user-images.githubusercontent.com/32019999/215538033-b8f91206-1c36-4cca-9428-770235d9ccd5.png)
![Screenshot_2023-01-30_21_47_06](https://user-images.githubusercontent.com/32019999/215538040-346eacf8-7d38-4748-8ad1-7b274ca96f79.png)
![Screenshot_2023-01-30_21_47_07](https://user-images.githubusercontent.com/32019999/215538042-b51948d1-5328-4bd1-9a8b-4d737c4c7a7e.png)
![Screenshot_2023-01-30_21_48_20](https://user-images.githubusercontent.com/32019999/215538043-68bf7143-ec77-4c72-95fb-88bd0f72085e.png)

whenever i am trying to open the php.int
it is showing like this
![opening file error](https://user-images.githubusercontent.com/32019999/215538668-eef32ebe-cff2-41f5-81a8-b0e8605dcdcd.png)

please solve this issue

**Comment by digininja** [comment]
You are getting the error from vim because you already have the file open
for editing in a different terminal. Change to that and use that one
instead of trying to use a new editor.

My guess would be you made the change in one, did a change in another and
got the two out of sync.

Get rid of the other editor and then make the change to the file again to
enable it.

**Comment by himz123** [comment]
I closed my machine
restarted everything

Before- 
![before](https://user-images.githubusercontent.com/32019999/215546813-e9008abb-d392-48ce-a7f7-0511eaa65410.png)

when Off
![when off](https://user-images.githubusercontent.com/32019999/215546917-4fe47bad-1393-4629-8444-24d2ec95b2dc.png)

after making it on 
![Screenshot_2023-01-30_22_47_37](https://user-images.githubusercontent.com/32019999/215547841-bb359fbf-dfdc-4a50-b65e-6145f55d3f24.png)


After making changes in php.ini
still the same.
![after](https://user-images.githubusercontent.com/32019999/215547023-fdf77c9a-6a52-4a35-acd4-051e0e07a70f.png)

I made that enabled but when I enabled my **module gd**, it gets disabled automatically.
What can I do now? It is still not resolved

**Comment by digininja** [comment]
Did you restart Apache after turning it back on?

**Comment by himz123** [comment]
yes
I used the command apachectl restart

**Comment by himz123** [comment]
yes
I have seen through the folder also
it is in the apache2 folder 
I have save it by using :wq

**Comment by himz123** [comment]
![saved file](https://user-images.githubusercontent.com/32019999/215550605-91040dfd-b6c8-412a-aec4-3c5c92f36340.png)

**Comment by himz123** [comment]
One thing that is very strange
I lost my conf.d folder in apache2 of 8.1

**Comment by himz123** [comment]
Maybe the error is from this file.
I am not able to delete or rm this file.
I just run the update and upgrade commands and now this is showing.

what can I do now to remove this swp file?


![unknown file](https://user-images.githubusercontent.com/32019999/215555663-08aee84d-042a-4472-b106-4b2a493a08f1.png)

**Comment by digininja** [comment]
If you look at the setup page, it is running on php 8.2.1, you are editing
files in the 8.1 directory. That is why the changes you are making are
having no affect.

**Comment by himz123** [comment]
You are genius
Thanks mate

Finally i did it
![finally](https://user-images.githubusercontent.com/32019999/215569380-3b3b2e5a-2090-4eba-a9cf-7d0a4a4d65be.png)
