### ISSUE TITLE
Blank Page Bug

### ISSUE THREAD

**Issue by 0067sdsm** [digininja/DVWA#534]
Before you raise a bug, please make sure you have fully read the README, especially if your bug relates to configuring the database.

Issues will be closed if the answer is in the README and no obvious attempts have been made to follow it.

Support will only be given for users running the latest pull of code from GitHub. Not a tagged release, not a pre-installed app, not a ZIP you got from a mate.

**Describe the bug**
So when i go to the login.php its just blank, apache2 is runnning/ setup.php works just login.php. Please help :).

**To Reproduce**
i dont understank the question. Kali Linux, apache2.

Steps to reproduce the behaviour:
1. Go to ipaddress/DVWA/setup.php (works)
2. Click on Add /reset databases or something like that
3. ipaddress/DVWA/setup.php# (just blank page (nothing))

**Screenshots**
![image](https://user-images.githubusercontent.com/115708721/215882831-534c61f0-0433-420d-9095-71210a6f8a77.png)

**System (please complete the following information):**
 - OS: Kali
 - MariDB i think (i just ran sudo mysql)
 - PHP Version idk
- none i think

**Comment by digininja** [comment]
Please put a bit of effort in and work out what version of php and database
you are using.

Did you follow all the setup instructions? Is the database definitely
running? Can you connect to it using the credentials in the config file?

Also provide the last five lines from the Apache error log created after
the page is shown.

**Comment by 0067sdsm** [comment]
yes i went through the config files and and i serached for the "allow_" and edited that and also the credentials. I also added the user in mysql. Ima be honest i have no idea what im doing @__@, i was following a video.

**Comment by 0067sdsm** [comment]
and the logs i have no idea how to acces, i just run "systemctl start apache2"

**Comment by digininja** [comment]
Well, this is a perfect learning experience for you. Being able to do web
app testing is a lot more than just being able to use a web site, you need
to understand the full stack including the database and web server layers.

The README shows you how to confirm that you setup the database correctly,
try following those steps.

For the logs, try searching for how to read the apache web server logs,
there are loads of sites out there that tell you how to do it.

I'm prepared to help, but you have to put effort in yourself. As a
hacker/tester, when you get stuck, you have to be able to do research to
find out what is wrong and how to fix it, not just ask others for help. If
you do need help, you need to be able to show what you've already done to
try to help yourself.

**Comment by 0067sdsm** [comment]
Ye thanks for the help :)

**Comment by 0067sdsm** [comment]
i read it and im pretty sure m stuff is set up correctly, plus i dont think there is nothing related to my issue :/

**Comment by digininja** [comment]
See this section and prove you've got the database credentials correct.

https://github.com/digininja/dvwa#access-denied-running-setup

And you still need to get those error logs.

**Comment by galoget** [comment]
Quick hint for @0067sdsm, try searching for a file called `error.log`, this file should be related to the web server that you are using (e.g. Apache).

If you do not know about Linux Directory Structure, try reading: https://www.geeksforgeeks.org/linux-directory-structure/

Good luck!

**Comment by digininja** [comment]
Gone silent so closing.
