### ISSUE TITLE
Deprecated: Directive 'allow_url_include' is deprecated in php7.4 & php8

### ISSUE THREAD

**Issue by PatheticCode** [digininja/DVWA#538]
**Describe the bug**
the allow_url_include directive is deprecated from php7.4 onwards  https://www.php.net/manual/en/migration74.deprecated.php
I noticed it in php8, therefore mentioning php8 here.

**To Reproduce**
1. install php8
2. copy https://github.com/digininja/DVWA/blob/master/php.ini to the correct php-ini folder 
3. run php --ini
4. get 'Deprecated: Directive 'allow_url_include' is deprecated in Unknown on line 0'

**Logs**
Include the last five lines of the Apache log file from directly after the problem happened.

**Expected behaviour**
file inclusion labs should not longer depend on allow_url_include or mention the issue directly in the readme.md as well as on the setup.php page.

**What have you done to help fix the issue yourself?**
--

**System (please complete the following information):**
 - OS: custom OS (might not yet be an issue on Debian/Ubuntu, but soon)
 - PHP Version > 7.4

**Comment by digininja** [comment]
I've done quite a bit of reading and I agree that it is deprecated, but I can't see what that actually means. There is nothing to say what will happen once it has gone. Will it be on by default or off, or has it been replaced by something else.

Any ideas?

**Comment by digininja** [comment]
I've just had a play and the feature is still working and there is no info on what will happen when it is removed or when it will be removed, so I'm going to close this but keep it in mind for when the feature breaks in the future.
