### ISSUE TITLE
dvwa PHP fatal error

### ISSUE THREAD

**Issue by conphong2k** [digininja/DVWA#544]
[php:error] [pid 8211] [client 127.0.0.1:47936] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown error while connecting in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:498\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(498): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 498

**Comment by digininja** [comment]
Please use the correct issue template for problems and include all the requested information.

Also read the readme file, the answer is likely to be in there.
