### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by k-0-i** [digininja/DVWA#545]
![image](https://user-images.githubusercontent.com/95953449/225037821-a84a9853-8255-4df6-ae86-52aecf96162c.png)

**Comment by digininja** [comment]
What version of php on what OS?

Are you using the latest code from GitHub?

**Comment by k-0-i** [comment]
> 

I've solved this issue and it's my PHP version that is causing trouble, thank you very much. What is the PHP version number required for this project?

**Comment by k-0-i** [comment]
I started using 5.3 and reported an error, and I can use it when I change to 5.6. Anyway, thank you very much for your help. Just now, I worked fine with 7.3.

**Comment by digininja** [comment]
It was originally written to work with 5.x so should mostly work but seeing
as 5.x ended life at the end of 2018 nothing added since then has been back
tested.

**Comment by k-0-i** [comment]
Oh oh understood, thanks, good night.
