### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by makswell-chen** [digininja/DVWA#553]
dear author:
im gonna install DVWA on kali linux running in the Vmware workstation Pro 17.i've followed the guidence of the installation vedio posted in the README.md on youtube and obeyed step by step but after clicking  the "Create/Reset databse" buttom on the setup.php page i figured out that i cannot keep up with the step in the vedio,And ive followed the reminder in the README.md file. after you clicking the Create/Reset databse buttom and you are able to click the 'guestbook' table was created,but im caught the trouble like this:

Uploading DVWA client - VMware Workstation 2023-05-06 17-21-14.mp4…
what causes this problem?

**Comment by makswell-chen** [comment]
Uploading DVWA client - VMware Workstation 2023-05-06 17-21-14.mp4…

**Comment by digininja** [comment]
Please reopen this ticket and provide the information requested in the
ticket template.

**Comment by makswell-chen** [comment]
im sorry i dont get your words ,what should i do?im new for cybersecurity learning.sorry.

**Comment by digininja** [comment]
Was this supposed to be a video?

> Uploading DVWA client - VMware Workstation 2023-05-06 17-21-14.mp4…

I need to know what is wrong, you say after you click the create button, but what happened, what was the error?

Can I get the last five lines from the Apache error and access log files after you've had the problem.

Which version of DVWA are you using, where did you get it from?

**Comment by makswell-chen** [comment]
dear author:
im sorry for not making it clear,ive already made a vedio that can express my problem on youtube,pls check the vedio:https://www.youtube.com/watch?v=8D-pZOz4IPY .
and for the version of kali linux ive been used ,ive check it :
└─$ cat /etc/os-release 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2023.1"
VERSION_ID="2023.1"
ive just downloaded it from the offical website several days ago and i set up it on the Vmware workstation pro 17 which im also downloaded several days ago.
for the 4:00 duration in this vedio,i apologize that i didnt show the host machine screen,this shows that the PHP configuration you told us follow to change in the README.md file posted on github in DVWA project.
thank you for patient answer.

**Comment by digininja** [comment]
Why do you want to click things? Those messages say what has been done and
they've all been completed successfully.

**Comment by makswell-chen** [comment]
ah,when i skip the click things all the else things can successfully work,thanks.

**Comment by digininja** [comment]
There was nothing to skip, there is no instruction to click anything and it
isn't clicked in the video.
