### ISSUE TITLE
dvwa white page 

### ISSUE THREAD

**Issue by marwan2elsayyad** [digininja/DVWA#554]
hi after following the main branch here on GitHub and following the installation video I faced a problem after I reset the database from dvwa and then scrolled down shown below 
Username: Unknown
Security Level: Impossible
Locale: en
SQLi DB: MySQL 
and that appeared on the video 
Username: admin
Security Level: Impossible
Locale: en
SQLi DB: MySQL 

also, every page I opened showed as a 
![0](https://user-images.githubusercontent.com/58485204/236628804-6318a066-8d49-432f-9b57-9e860ed93f00.jpg)
white page without any details 
![00](https://user-images.githubusercontent.com/58485204/236628812-451ee458-a37a-4c37-9e17-60aa7d5722d6.jpg)

**Comment by digininja** [comment]
Is there any content at all? Did you try viewing the source?

Give me the last five lines of the apache error and access log when you see the blank page.

Have you turned disable authentication off in the config file?

What version of the app are you using?

Can you show that the database connection is setup correctly? Use the readme, that tells you how to login to show it works.

**Comment by hasnain-malik007** [comment]
exactly the same problem I facing on dvwa, bro please tell me that how can see the apache logs or any other log?

**Comment by digininja** [comment]
DVWA is designed as a learning experience, have you tried searching for how to view Apache logs in Kali?

**Comment by touhidulshawan** [comment]
![image](https://github.com/digininja/DVWA/assets/37136490/114c8196-0cfa-4d34-855f-f3dbbf591693)

Same issue here. Setup successful but when I go to the login page it shows no content.
Page source `<html data-lt-installed="true"><head></head><body></body></html>`
![2023-05-15-19:59:18-screenshot](https://github.com/digininja/DVWA/assets/37136490/408f09c7-236a-4688-8adf-002510fbf3a0)

@digininja can you please tell me the problem?

**Comment by digininja** [comment]
No one has sent any logs so I can't tell anyone anything.

@touhidulshawan That isn't the source for the login page, the login page starts:

```
<!DOCTYPE html>
   <html lang="en-GB">
   <head>
```

**Comment by touhidulshawan** [comment]
@digininja fixed my problem. It was my mistake 😥. I didn't notice that `allow_url_include = On` was Off in my PHP config.
Thanks for giving your time 🙂

**Comment by digininja** [comment]
That would only have affected the LFI and RFI labs and maybe only one or two levels on those. Whatever was causing the problem, that wasn't it.

**Comment by touhidulshawan** [comment]
I satisfied all the red on the setup.php except for `reCAPTCHA key: Missing`. After that my problem was fixed

**Comment by digininja** [comment]
@touhidulshawan looking at your setup page, you had display_errors turned off, that was why you got an empty page.

**Comment by digininja** [comment]
Gone quiet, closing.
