### ISSUE TITLE
Image not uploading

### ISSUE THREAD

**Issue by Souparno10** [digininja/DVWA#565]
Image is not uploading in the Upload section.
- Docker image of Metasploitable.
- Kali Linux on Azure
- No error.
- Tried changing permissions to 755.

**Comment by digininja** [comment]
As requested, please give the last five lines in the access and error log
files from around when the problem happens.

**Comment by Souparno10** [comment]
Actually I'm new in computers and don't know how to get the logs.

**Comment by Souparno10** [comment]
172.17.0.1 - - [29/Jun/2023:03:55:35 -0400] "GET /dav/ HTTP/1.1" 200 691 "http://172.17.0.2/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
172.17.0.1 - - [29/Jun/2023:03:55:35 -0400] "GET /icons/back.gif HTTP/1.1" 200 216 "http://172.17.0.2/dav/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0$
172.17.0.1 - - [29/Jun/2023:03:55:35 -0400] "GET /icons/blank.gif HTTP/1.1" 200 148 "http://172.17.0.2/dav/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.$
172.17.0.1 - - [29/Jun/2023:03:55:37 -0400] "GET /dvwa/ HTTP/1.1" 302 - "http://172.17.0.2/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
172.17.0.1 - - [29/Jun/2023:03:55:37 -0400] "GET /dvwa/login.php HTTP/1.1" 200 1289 "http://172.17.0.2/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Sa$
172.17.0.1 - - [29/Jun/2023:03:55:41 -0400] "POST /dvwa/login.php HTTP/1.1" 302 - "http://172.17.0.2/dvwa/login.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/$
172.17.0.1 - - [29/Jun/2023:03:55:41 -0400] "GET /dvwa/index.php HTTP/1.1" 200 4585 "http://172.17.0.2/dvwa/login.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrom$
172.17.0.1 - - [29/Jun/2023:03:55:43 -0400] "GET /dvwa/vulnerabilities/upload/ HTTP/1.1" 200 4519 "http://172.17.0.2/dvwa/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, lik$
172.17.0.1 - - [29/Jun/2023:03:55:49 -0400] "POST /dvwa/vulnerabilities/upload/ HTTP/1.1" 200 4558 "http://172.17.0.2/dvwa/vulnerabilities/upload/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537$

**Comment by Souparno10** [comment]
Error is coming after trying to upload the image
![image](https://github.com/digininja/DVWA/assets/95336246/32466279-bfbe-4abf-8005-d4e21aef1ae8)

**Comment by digininja** [comment]
Show the permissions of the uploads directory and get a screenshot of the setup page.

**Comment by Souparno10** [comment]
I'm not much pro in computers. Here are all the screenshots using ls -l
![image](https://github.com/digininja/DVWA/assets/95336246/72350cfc-896f-48b0-a620-a0b06a600977)
![image](https://github.com/digininja/DVWA/assets/95336246/53cc5e6f-816b-4e3f-8192-d1dc19785ebe)
![image](https://github.com/digininja/DVWA/assets/95336246/32a9c17c-7db9-4633-967e-a6b07e16b3a2)

**Comment by digininja** [comment]
I don't know what version you are running, but it isn't the latest so it isn't supported on here. Please follow the readme to install the latest version and try again on that.
