### ISSUE TITLE
Could not connect to the database service. Please check the config file. Database Error #1045: Access denied for user 'dbauser'@'localhost' (using password: YES).

### ISSUE THREAD

**Issue by Jon1oh** [digininja/DVWA#566]
Hello. I want to set up DVWA on my own Ubuntu virtual machine hosted on my Windows computer but am facing some trouble. My virtual machine has an IP Address of 192.168.33.10. Here are my current configurations. Any help would be very much appreciated!!

**Setup Configurations**
![image](https://github.com/digininja/DVWA/assets/92898239/33638adc-cc1d-48fb-8335-c44edaf44a00)

**config.ini.php configurations**
![image](https://github.com/digininja/DVWA/assets/92898239/99fe81ba-1037-4144-a3ec-9d3e90f460ee)

**root user access to SQL Database works**
![image](https://github.com/digininja/DVWA/assets/92898239/474b2e4a-a958-4cc2-9e36-af2790209bf7)

**dbauser failed to access SQL Database**
![image](https://github.com/digininja/DVWA/assets/92898239/fdbcd850-263f-4733-b385-095a4d64389d)

I used the same password from the config.ini.php file to authenticate into the SQL database but I still get an error code 1045. Am I getting the error because of the configuration of my IP Addresses in the above screenshots?

**Comment by Jon1oh** [comment]
I managed to set up and access the DVWA site on my local Windows machine.
![image](https://github.com/digininja/DVWA/assets/92898239/eb736883-9456-4418-91b8-ec85e9922fe8)

Now, I want to try to access the SQL database of DVWA from my Kali Linux machine. However, I am unable to access the database as root and my dbauser. 
![image](https://github.com/digininja/DVWA/assets/92898239/959437be-32cc-49d2-9d64-12385534e3d3)

Please advice. Any help is very much appreciated!

**Comment by digininja** [comment]
My guess would be that the database server is not listening on the network,
just locally.

You'll need to look into database configuration to change that.

**Comment by Jon1oh** [comment]
**My dbauser can access the SQL database from the Windows command prompt**
![image](https://github.com/digininja/DVWA/assets/92898239/81d293bd-f695-4e26-bc27-b58d054262e5)

Do you mean I should check the configurations inside the config.inc.php?

**Comment by digininja** [comment]
This isn't a dvwa issue, it's the way you've got Mariadb setup. You can
tell it which interfaces and ports to listen in and it's probably set to
only listen on localhost.

**Comment by Jon1oh** [comment]
Okay, I'll try to look into that. Thanks.

**Comment by Jon1oh** [comment]
I faced some issues and had to restart my configuration again.

**DVWA Setup Configurations**
![image](https://github.com/digininja/DVWA/assets/92898239/152fc484-0e29-4539-808a-4d66e0c3fd74)

**config.inc.php configurations**
![image](https://github.com/digininja/DVWA/assets/92898239/70e11953-5239-439a-8d55-3552e33f738e)

I am stuck here again and I forgot how I solved it earlier. My password for the my dbauser is the same as the password inside the config.inc.php file.

**Comment by digininja** [comment]
Prove you can login on the command line using those credentials. That error isn't a credential error so my guess would be the database server either isn't running or you've changed how it is listening on the network.

**Comment by Jon1oh** [comment]
I can't access using the dbauser credentials. Only root works 😭 
![image](https://github.com/digininja/DVWA/assets/92898239/63c6ab0c-6fce-4861-abdf-b900fe0745cb)

**Comment by Jon1oh** [comment]
My dbauser cannot access the database even though I've already created the dbauser in the database.

![image](https://github.com/digininja/DVWA/assets/92898239/34e8e8ac-029c-4572-b6e2-9a0dc452bca1)

**Comment by digininja** [comment]
I don't know what you've done, it is either the username or password that is incorrect,

Remember, the config.inc.php file is what tells DVWA the creds to use to connect to the database, they aren't what the database uses to store it's list of users.

**Comment by Jon1oh** [comment]
Ok I’ll try again and update how it goes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jon1oh** [comment]
I have restarted setting up DVWA from scratch on my Ubuntu machine. This is where I am stuck now.

![image](https://github.com/digininja/DVWA/assets/92898239/ba5d654c-6cf9-43d2-bd49-4df07cd2fdba)

I can't login to the MariaDB server using my dbauser.
![image](https://github.com/digininja/DVWA/assets/92898239/f9220a7f-d6e3-4988-9d38-2fc797c8f4ca)

Here are the configurations in the config.inc.php file.
![image](https://github.com/digininja/DVWA/assets/92898239/1ac0cf81-e820-453b-aa34-84e9a6cf6169)

**Comment by digininja** [comment]
Did you add the user back to Mariadb? Remember the config file has nothing
to do with the database, you have to set that up first, be able to log into
that, then configure dvwa.

**Comment by Jon1oh** [comment]
This is me logging into the accessing the database as **root user** to get the users table.
![image](https://github.com/digininja/DVWA/assets/92898239/74f33359-6756-4e7f-99a7-caa4b9f17e44)

Here are the configurations I made to the dbauser in the database (excuse my typos)
![image](https://github.com/digininja/DVWA/assets/92898239/e4be07fa-e1c3-4ad2-a999-6b8d77dc279f)

This is me logging into the database as the dbauser immediately after creating the dbauser and granting it permissions.
![image](https://github.com/digininja/DVWA/assets/92898239/aa7b5b98-2681-4e81-9db1-6f003d6403b6)

**Comment by digininja** [comment]
You are saying the user can log in from 192.168... but you are then trying
to log in from localhost which is 127.0.0.1.

Either change the user to log in from either localhost or anywhere, or
specify the IP as the host on the command line.

**Comment by Jon1oh** [comment]
are you saying I should change the IP address I have specified inside the database for my dbauser from 192.168.. to 127.0.0.1?

**Comment by digininja** [comment]
Yes, or wildcard to allow from any IP.

**Comment by Jon1oh** [comment]
This is what I have done:

1. Configure the dbauser credentials inside the config.inc.php file
![image](https://github.com/digininja/DVWA/assets/92898239/d3789628-6e80-4754-b661-57062633b76a)

2. Access the MariaDB as root and create the dvwa database and the dbauser.
![image](https://github.com/digininja/DVWA/assets/92898239/35bd0c2b-ec2a-42d8-a2ff-2088f9159749)

3. Access the MariaDB database as the dbauser.
![image](https://github.com/digininja/DVWA/assets/92898239/d82b60db-61f3-4fb6-a3fa-c544cb36bbd6)

It works!!

I have successfully set up the DVWA website on my Ubuntu machine.
![image](https://github.com/digininja/DVWA/assets/92898239/a0cce204-a7e5-44cf-b347-2fb28a012621)
