### ISSUE TITLE
I have problem about password changing in CSRF

### ISSUE THREAD

**Issue by cokestrawberry** [digininja/DVWA#567]
- Where did you get DVWA from?
=> from GitHub (I've cloned it)

- What OS are you installing it on?
=> Debian 12.x 64-bit Arm (Kali Linux)

- The error you got when you got stuck.
=> Before I start attack, I've just tried to change password of admin with given web page. But when I checked whether it was successful or not in "Test Credentials" page, the password does not changed. 

- What you have tried to do yourself to fix the problem.
=> I saw a notice below(about default setting of Lax) and tried to change samesite cookie value but I think it doesn't work...
<img width="278" alt="스크린샷 2023-07-11 오전 11 54 45" src="https://github.com/digininja/DVWA/assets/48722427/8e9c5fbd-c45d-4f8e-a353-b8c9c8e943c5">
<img width="507" alt="스크린샷 2023-07-11 오전 11 56 40" src="https://github.com/digininja/DVWA/assets/48722427/1c58b22f-c93b-415d-b721-4071420084eb">

**Comment by digininja** [comment]
What level are you using?

**Comment by cokestrawberry** [comment]
I'm in now low level. But same problem in other difficulties.

**Comment by digininja** [comment]
It works for me but there was a warning thrown so I've made a change, pull the repo again and see if it works now.

**Comment by cokestrawberry** [comment]
Thanks! I’ll wait for it :)

**Comment by digininja** [comment]
No waiting, I did it before I replied to you.

**Comment by cokestrawberry** [comment]
I tried again today, but still same issue...
Is there any setting that I have to try to change?

**Comment by digininja** [comment]
Try resetting the database and doing the test login using the default
credentials to see if that works.

Then try changing the password and try both the test login form and the
main one to see if it changed.

**Comment by cokestrawberry** [comment]
<img width="272" alt="스크린샷 2023-07-18 오전 11 06 20" src="https://github.com/digininja/DVWA/assets/48722427/32f91e95-b3bf-4459-93a0-10a1cbfa2f1d">
<img width="263" alt="스크린샷 2023-07-18 오전 11 07 12" src="https://github.com/digininja/DVWA/assets/48722427/c019a999-da8d-4966-a188-922944415144">
<img width="266" alt="스크린샷 2023-07-18 오전 11 08 32" src="https://github.com/digininja/DVWA/assets/48722427/31df1833-3121-4f04-849a-043ae1fb6280">
<img width="281" alt="스크린샷 2023-07-18 오전 11 09 18" src="https://github.com/digininja/DVWA/assets/48722427/56f5d469-4b49-4616-acf2-ad03998611a2">


...seems still doesn't work  :(

**Comment by digininja** [comment]
It works fine for me so I'm guessing it is something on your system that is causing the problem.

You need to put a proxy in place and look at the traffic, see what is actually happening. If you don't already know how to, this is the time to pick a good intercepting proxy, such as Burp or ZAP, get it installed, and have a look at the traffic as it flows past. Check what you think is being sent to the server is actually being sent.

**Comment by cokestrawberry** [comment]
As I've found another problem in other session, it would better to destruct and re-install docker container...
Thanks for your advice!
