### ISSUE TITLE
The GUI of setup.php, login.php, index.php got error after installing php-gd (php8.1), I can access the index.php page before

### ISSUE THREAD

**Issue by DuongThai29** [digininja/DVWA#573]
Database Setup

Click on the 'Create / Reset Database' button below to create or reset your database.
If you get an error make sure you have the correct user credentials in: " . realpath( getcwd() . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR . "config.inc.php" ) . "

If the database already exists, it will be cleared and the data will be reset.
You can also use this to reset the administrator credentials (\"admin // password\") at any stage.

Setup Check
{$SERVER_NAME}

{$DVWAOS}

PHP version: " . phpversion() . "
{$phpDisplayErrors}
{$phpDisplayStartupErrors}
{$phpURLInclude}
{$phpURLFopen}
{$phpGD}
{$phpMySQL}
{$phpPDO}

Backend database: {$database_type_name}
{$MYSQL_USER}
{$MYSQL_PASS}
{$MYSQL_DB}
{$MYSQL_SERVER}
{$MYSQL_PORT}

{$DVWARecaptcha}

{$DVWAUploadsWrite}
{$bakWritable}

Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.

allow_url_fopen = On
allow_url_include = On

These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

" . tokenField() . "

**Comment by digininja** [comment]
You haven't got php installed or enabled. Follow the README for instructions

**Comment by DuongThai29** [comment]
Hi Robin,

I've got the latest php installed before.
[image: image.png]
The problems occurred when I have installed php-gd. Please help me to solve
this.

Vào Th 4, 16 thg 8, 2023 vào lúc 15:13 Robin Wood <
***@***.***> đã viết:

**Comment by digininja** [comment]
You see what you are getting when php isn't installed or working, that is
why you are seeing unprocessed php.

**Comment by DuongThai29** [comment]
Hi Robin,

I’m pretty sure that I have installed php before the problem occurred
because I can configure in setup.php page, login.php page and can access to
index.php page. After that, I figure all errors have been existed, like
xxx_errors = On in php.ini file. And when I installed php-gd and restart
apache2, the problem begins as mentioned before.

I’ll try to reinstall DVWA again but problem didn’t fix. Pls suggest the
resolution for this issue. Tks

**Comment by digininja** [comment]
It is php, I guarantee it. Reinstalling dvwa on its own won't fix things.

Check the page /phpinfo.php to see if that gives you any output.

**Comment by DuongThai29** [comment]
Hi Robin,

After reinstall php, the problem has been fixed. Thank for your support.

Regards!

Vào Th 4, 16 thg 8, 2023 vào lúc 18:09 Robin Wood <
***@***.***> đã viết:

> It is php, I guarantee it. Reinstalling dvwa on its own won't fix things.
>
> Check the page /phpinfo.php to see if that gives you any output.
>

**Comment by digininja** [comment]
Glad it is fixed, please close the issue.

**Comment by hoang-himself** [comment]
Hello, fellow Crypto & NetSec learner. Just a reminder that you can close this issue as resolved.

**Comment by DuongThai29** [comment]
Yes, it's done.

**Comment by hoang-himself** [comment]
That's not how GitHub works. I'll just let @digininja close this then.
