### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Princedenrik** [digininja/DVWA#582]
[Hello I don’t know why my dvwa is not opening properly.I have configured it step by step but still can’t get login access.Please I need assistance.](https://imgur.com/a/4vNnBxx) Questions here may or may not be answered depending on the state of the question, to increase your chance, read this before asking [Asking For Technical Help](https://digi.ninja/blog/asking_for_help.php).

Basically, the more details you give, the more chance of getting an answer. We need at least:

- Where did you get DVWA from?
- What OS are you installing it on?
- Last five lines from the web server access and error log from the time the error occurred if you got that far.
- The error you got when you got stuck.
- Any previous errors.
- What you have tried to do yourself to fix the problem.

Support will only be given for users running the latest pull of code from GitHub. Not a tagged release, not a pre-installed app, not a ZIP you got from a mate.

**Comment by digininja** [comment]
You don't have PHP installed or enabled. See the README for more information.
