### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Princedenrik** [digininja/DVWA#583]
Hello I don’t know why my dvwa is not opening properly.I have configured it step by step but still can’t get login access.Please I need assistance.](https://imgur.com/a/4vNnBxx)

**Comment by digininja** [comment]
You've not got php installed or enabled.

Please read the readme for full instructions.

**Comment by Princedenrik** [comment]
Php is installed and enabled.am running version 8.2 and also.Am still getting the same results.

**Comment by digininja** [comment]
No it isn't. That is why you are seeing raw PHP code, it isn't being parsed
by the PHP engine.

**Comment by Princedenrik** [comment]
Please can you direct me on how to get it passed or enable

**Comment by digininja** [comment]
See the readme.

**Comment by Princedenrik** [comment]
I have seen the php configurations in the readme.
Allow_url_include =On
Allow_url_fopen= On
I don’t  Know what else to do

**Comment by digininja** [comment]
You've not told me any information about OS or distro so I can't help any
more. The best thing for you to do is to go and talk to the support
community for whatever OS you are using and ask them how to get PHP
working. Once it is working, and you've confirmed that, then come back to
DVWA.

**Comment by Princedenrik** [comment]
Sorry ,I’m using Kali Linux

**Comment by digininja** [comment]
Have a chat with the Kali team then.

https://forums.kali.org/
