### ISSUE TITLE
XSS Stored  i cant open xss stored vulnerability page

### ISSUE THREAD

**Issue by AntoniMatrix** [digininja/DVWA#585]
Warning: Undefined global variable $___mysqli_ston in C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php on line 536

Fatal error: Uncaught TypeError: mysqli_query(): Argument 
#1 ($mysql) must be of type mysqli, null given in C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php:536 Stack trace: 
#0 C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php(536): mysqli_query(NULL, 'SELECT name, co...') 
#1 C:\xampp\htdocs\DVWA\vulnerabilities\xss_s\index.php(72): dvwaGuestbook() 
#2 {main} thrown in C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php on line 536

**Comment by digininja** [comment]
This is line 536 of `dvwa\includes\dvwaPage.inc.php`:

```
536 function dvwaRedirect( $pLocation ) {
```

So looks like you aren't running the latest version.
