### ISSUE TITLE
Blind SQLi Error

### ISSUE THREAD

**Issue by samiux** [digininja/DVWA#590]
Before you raise a bug, please make sure you have fully read the README, especially if your bug relates to configuring the database.

Issues will be closed if the answer is in the README and no obvious attempts have been made to follow it.

Support will only be given for users running the latest pull of code from GitHub. Not a tagged release, not a pre-installed app, not a ZIP you got from a mate.

**Describe the bug**
Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 or 1 = 1 -- '' at line 1 in /var/www/html/vulnerabilities/sqli_blind/source/low.php:12 Stack trace: #0 /var/www/html/vulnerabilities/sqli_blind/source/low.php(12): mysqli_query(Object(mysqli), 'SELECT first_na...') #1 /var/www/html/vulnerabilities/sqli_blind/index.php(34): require_once('/var/www/html/v...') #2 {main} thrown in /var/www/html/vulnerabilities/sqli_blind/source/low.php on line 12

**Expected behaviour**
No error

**System (please complete the following information):**
 - DVWA docker installation OS Debian 12

**Browser/Proxy (please complete the following information):**
 - OS - The one you are running the browser in: [e.g. Windows 10]
 - Browser Firefox 119.0

**Comment by digininja** [comment]
Well spotted, see if the fix I've just put in works.

**Comment by samiux** [comment]
I also find SQL injection also has the same error.

**Comment by digininja** [comment]
Basic SQLi should have, that is error based.

**Comment by samiux** [comment]
Agree.

Please change it back.  Thanks.

**Comment by duanshi21** [comment]
Please tell me if this problem has been fixed

**Comment by digininja** [comment]
Why don't you try it and find out?

**Comment by CSpanias** [comment]
I am trying to work on the Blind SQLi but I also get a "Fatal error: Uncaught mysqli_sql_exception: Unknown column '3' in 'order clause'..." instead of the expected "User ID is MISSING from the database." message. 

I played around with the "display_errors" PHP configs, but did not manage to fix it. I see walkthroughs, such as [this](https://www.youtube.com/watch?v=uN8Tv1exPMk), from a couple of years ago and it seem to work fine. 

Any guidance of how to fix that behaviour would be highly appreciated!

**Comment by digininja** [comment]
Please create your own issue and detail exactly what you are doing. If you are getting an error message on blind then your install isn't working correctly.

When you create the issue, please fill in all the requested fields.
