### ISSUE TITLE
I get Access denied. accessing setup.php or any other page

### ISSUE THREAD

**Issue by igotfr** [digininja/DVWA#599]
Questions here may or may not be answered depending on the state of the question, to increase your chance, read this before asking [Asking For Technical Help](https://digi.ninja/blog/asking_for_help.php).

Basically, the more details you give, the more chance of getting an answer. We need at least:

- Where did you get DVWA from?
from github
- What OS are you installing it on?
Fedora 37
- Last five lines from the web server access and error log from the time the error occurred if you got that far.
- The error you got when you got stuck.
I get Access denied. accessing setup.php or any other page
- Any previous errors.
- What you have tried to do yourself to fix the problem.
- PHP version
8.1.25

Support will only be given for users running the latest pull of code from GitHub. Not a tagged release, not a pre-installed app, not a ZIP you got from a mate.

**Comment by digininja** [comment]
can you send the last five lines from your Apache log, a screenshot of the error, what directory have you installed dvwa into and what is the document root line in the Apache config file.

**Comment by igotfr** [comment]
@digininja $ cat /var/log/httpd/error_log
```
[Wed Jan 10 15:34:11.275225 2024] [mpm_event:notice] [pid 4801:tid 4801] AH00489: Apache/2.4.58 (Fedora Linux) configured -- resuming normal operations
[Wed Jan 10 15:34:11.275334 2024] [core:notice] [pid 4801:tid 4801] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Jan 10 15:34:19.232953 2024] [autoindex:error] [pid 4815:tid 4919] [client ::1:34628] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Wed Jan 10 15:34:35.529457 2024] [proxy_fcgi:error] [pid 4815:tid 4914] [client ::1:34630] AH01071: Got error 'Unable to open primary script: /var/www/html/DVWA/index.php (Permission denied)'
[Wed Jan 10 15:34:47.263306 2024] [proxy_fcgi:error] [pid 4816:tid 4948] [client ::1:37478] AH01071: Got error 'Unable to open primary script: /var/www/html/DVWA/setup.php (Permission denied)'
```

**Comment by digininja** [comment]
Read the third line down

**Comment by igotfr** [comment]
@digininja sorry, I didn't understand what the third line means:
```

**Comment by igotfr** [comment]
@digininja 
![image](https://github.com/digininja/DVWA/assets/32280512/3aae24da-ed5d-4f9c-8f91-609433e5cb2e)

I have installed the dvwa on directory /var/www/html

$ /etc/httpd/conf/httpd.conf
```
DocumentRoot "/var/www/html"
```

**Comment by digininja** [comment]
But where are the files? I bet they aren't in that directory. Are they in
/var/www/html/DVWA ?

**Comment by igotfr** [comment]
@digininja yes, the files are in /var/www/html/DVWA

**Comment by digininja** [comment]
So as the document root is /var/www/html and the files are in
/var/www/html/DVWA you'll need to browse to /DVWA to see them.

**Comment by igotfr** [comment]
@digininja I'm browsing http://localhost/DVWA/setup.php according the screenshot

**Comment by digininja** [comment]
I don't know then, it must be some odd Fedora thing.

Maybe file or directory permissions. Give a directory listing for
/var/www/html and /var/www/html/DVWA

**Comment by igotfr** [comment]
@digininja I put a test .php file with the same permission of the files in DVWA in the folder DVWA and it works

**Comment by digininja** [comment]
I still want to see the directory listings.

**Comment by digininja** [comment]
I should add please use `ls -al` rather than just `ls` so I can see the
full file permissions.

**Comment by igotfr** [comment]
@digininja 
![image](https://github.com/digininja/DVWA/assets/32280512/8fda77f1-e0d9-4150-a594-916433724dd4)

a.php is the file that I created for test that works

**Comment by digininja** [comment]
They look ok so I'm going to guess selinux is causing problems. I'm not a
Fedora user so can't help debug it any more but this page give a bit more
information.

https://serverfault.com/questions/1145844/how-to-enable-executing-php-files-in-fedora-apache

**Comment by sukalaper** [comment]
> @digininja ![image](https://private-user-images.githubusercontent.com/32280512/295683484-3aae24da-ed5d-4f9c-8f91-609433e5cb2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODE5MjUsIm5iZiI6MTcwNjA4MTYyNSwicGF0aCI6Ii8zMjI4MDUxMi8yOTU2ODM0ODQtM2FhZTI0ZGEtZWQ1ZC00ZjljLThmOTEtNjA5NDMzZTVjYjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA3MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNWY1ZWRjYzQ3YmY2ZWFlMzZhZDdmMDcyNzA2OGRiMDVjNzk3YjQzOTY0ZGJiMTlmZDRkZmMyYzU5OTExM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zBQ4Nn7H0SEFbuwPFQ1_0Ff7dQtdIDK9RHgUm7RzgAE)
> 
> I have installed the dvwa on directory /var/www/html
> 
> $ /etc/httpd/conf/httpd.conf
> 
> ```
> DocumentRoot "/var/www/html"
> ```

Hi, have you set on this line? 
1. `allow_url_fopen = On` 
2. `allow_url_include values = On`

**Comment by digininja** [comment]
They are nothing to do with this and won't affect it in any way.

**Comment by hoang-himself** [comment]
@igotfr have you resolved this issue?

My best guess is everything in `/var/www/` should be owned by `www`.
Try `chown -R www /var/www`.
