### ISSUE TITLE
Fatal Error after changing username and password

### ISSUE THREAD

**Issue by faheemkhan14** [digininja/DVWA#600]
**Describe the bug**
I followed your youtube tutorial and installed DVWA. It installed fine and was running however I changed he username and password in the 'config.inc.php' file and now at the login page it is giving me a 'Fatal Error...' The setup page shows up as normal still, just the login page doesn't.

**System (please complete the following information):**
VirtualBox
 - OS: Ubuntu Kali
   - PHP Version 8.2

<img width="1147" alt="Screenshot 2024-01-10 at 04 40 26" src="https://github.com/digininja/DVWA/assets/68590571/de280505-dcb5-4263-b81d-3a7dbfe41c58">
<img width="1148" alt="Screenshot 2024-01-10 at 04 39 48" src="https://github.com/digininja/DVWA/assets/68590571/b784b5bd-6d89-4c64-bd81-1be326b5ab47">

**Comment by faheemkhan14** [comment]
![Uploading Screenshot 2024-01-10 at 04.49.50.png…]()

**Comment by digininja** [comment]
My guess is you've mistaken the credentials the app uses to connect to the
database with the ones you use to log into the app and do changed the
config file without changing the database credentials so now the app can't
talk to it.

Put the credentials back to what they were when you first set it up and as
long as you did the database steps correctly it should all work fine.

**Comment by faheemkhan14** [comment]
I changed them back and it is still showing the same error now. Is there a way I can delete DVWA and all its files and start all over?

**Comment by digininja** [comment]
Why don't you take this as a chance to learn rather than tearing it down
and starting again?

If it worked once then it will again, you just have to put the correct
credentials back into the config file.

**Comment by faheemkhan14** [comment]
I did change them back to what they was before
User was admin and password was p@ssw0rd but it still showing the same fatal error

**Comment by faheemkhan14** [comment]
‘dvwa’ I mean

**Comment by digininja** [comment]
Show a screenshot of the entries in the config file and the error in the
browser.

If you've still got it show the command you ran to create the database user.

**Comment by faheemkhan14** [comment]
<img width="1151" alt="Screenshot 2024-01-10 at 18 51 57" src="https://github.com/digininja/DVWA/assets/68590571/41c9c04f-5b25-4180-be1f-3bdedae8ea57">
<img width="1154" alt="Screenshot 2024-01-10 at 18 53 27" src="https://github.com/digininja/DVWA/assets/68590571/3420418a-6465-4e1b-8273-0aa7ed101b27">

**Comment by faheemkhan14** [comment]
password is coming up as error here
![Uploading Screenshot 2024-01-10 at 18.58.53.png…]()

**Comment by faheemkhan14** [comment]
<img width="1154" alt="Screenshot 2024-01-10 at 18 58 53" src="https://github.com/digininja/DVWA/assets/68590571/cfae5a57-a79a-420d-afda-271dcfbdb252">

**Comment by digininja** [comment]
Watch the video again, in the step where the database user is created, do
the same but with a different username and password.

Put that username into the config file.

Send a screenshot of you creating the database user and the config file if
it doesn't work.

**Comment by faheemkhan14** [comment]
I cant create a database user because it just gives me the error whenever I try and put any username and password in. Tried the original dvwa and p@ssw0rd as it was before and tried the username and password i changed it to

**Comment by faheemkhan14** [comment]
<img width="1156" alt="Screenshot 2024-01-10 at 19 43 39" src="https://github.com/digininja/DVWA/assets/68590571/793347a1-d5a1-49b1-a3f9-1687ea6740ab">

**Comment by digininja** [comment]
You need to log into mariadb on the command line as the root user and
create a new database user.

**Comment by faheemkhan14** [comment]
but in order to login into mariadb you have to do 'mysql -u (username) -p(password) right?

**Comment by digininja** [comment]
It looks like your database server isn't running, start it with something
like

service mariadb start

Or maybe mysql, I'm not at a console to check.

**Comment by faheemkhan14** [comment]
still the same, username or password isnt working

**Comment by digininja** [comment]
Show the output from running the commands I suggested and

service mysql status

Or try mariadb, I can't remember which works on Kali.


It definitely doesn't look like the database isn't started.

And when you created the database user, did you create it with your name?

**Comment by faheemkhan14** [comment]
no i created the database with dvwa as the user

**Comment by digininja** [comment]
Check the status, I think you'll find it isn't running.

**Comment by faheemkhan14** [comment]
Yeah it says inactive

**Comment by faheemkhan14** [comment]
<img width="741" alt="Screenshot 2024-01-10 at 21 48 36" src="https://github.com/digininja/DVWA/assets/68590571/4f7b8b6b-dabf-4e5c-a206-ae37338422f4">

**Comment by digininja** [comment]
So run the start command

**Comment by faheemkhan14** [comment]
<img width="1149" alt="Screenshot 2024-01-10 at 22 33 30" src="https://github.com/digininja/DVWA/assets/68590571/3a35a30e-1ba1-4ec3-98f3-86f55347927d">

**Comment by digininja** [comment]
That error means Apache isn't running, you need to start that as well.

**Comment by faheemkhan14** [comment]
finallyy, thank you.

**Comment by digininja** [comment]
Glad it's working. Please close the ticket.
