### ISSUE TITLE
Problem in starting DVWA site

### ISSUE THREAD

**Issue by Nishantahirwal** [digininja/DVWA#601]
I installed DVWA by following every instructions but when i start my dvwa it shows blank white page (apache is working perfectly).
here are some screenshots of problem. Please help me ..
![Screenshot 2024-01-13 110629](https://github.com/digininja/DVWA/assets/102967445/2b807fff-0cfe-4970-81c5-6e4979d0a9da)
![Screenshot 2024-01-13 110710](https://github.com/digininja/DVWA/assets/102967445/85df28cb-50cf-4c64-97ee-2e70fa48ea42)

**Comment by digininja** [comment]
Please use the template provided when creating an issue to provide all the information requested, without this I've no idea what you did wrong.

**Comment by Nishantahirwal** [comment]
i am using linux  debian latest version, PHP 8.2, Maria DB latest, url, error all are on in php.ini, installed according to readme, Apache is working,
![Screenshot 2024-01-13 131847](https://github.com/digininja/DVWA/assets/102967445/7128d7cc-9f9f-4e00-bee4-3d4cb232f6d6)
![Screenshot 2024-01-13 132002](https://github.com/digininja/DVWA/assets/102967445/b1dca8c5-7e3b-4772-bdf2-eeda02e276db)
![Screenshot 2024-01-13 132022](https://github.com/digininja/DVWA/assets/102967445/3fc57410-331d-4abe-80bd-43a1c4d86f2d)
 but still showing blank white page when try to login

**Comment by digininja** [comment]
Last five lines from the Apache error log as the problem is happening
please.

I created the template so I don't have to keep coming back to you to ask
for what I need to help you.

**Comment by Nishantahirwal** [comment]
![Screenshot 2024-01-13 134044](https://github.com/digininja/DVWA/assets/102967445/ab5d9c6e-2a69-4d12-ac6c-5b19838128d9)
here please help

**Comment by digininja** [comment]
Please read the error messages and then do some research about what they
mean.

DVWA is a learning environment, learning how to read messages is a very
important part of app testing.

**Comment by Nishantahirwal** [comment]
Thanks brother i got it right now

**Comment by digininja** [comment]
Glad it is working.

Please close the ticket.
