### ISSUE TITLE
Installation Script for Debian

### ISSUE THREAD

**Issue by IamCarron** [digininja/DVWA#602]
I would like to propose to add my script to do an easy installation for (DVWA) on Debian-Based distros. 

Repository Information:

Repository URL: https://github.com/IamCarron/DVW-Script
Compatibility: Debian based distros
Installation Process:

1. Download the installation script:

   ```bash
   wget https://github.com/IamCarron/DVW-Script/blob/main/Install-DVWA.sh
   ```

2. Grant execution permissions to the script:

   ```
   chmod +x Install-DVWA.sh
   ```

3. Execute the script with superuser privileges:

   ```
   sudo ./Install-DVWA.sh
   ```

4. Follow the instructions provided by the script.

Feedback:
I welcome any feedback or suggestions to further improve and align the repository.

**Comment by IamCarron** [comment]
Right URL: https://github.com/IamCarron/DVWA-Script

**Comment by digininja** [comment]
I like the idea. There are a few extra things that need doing, such as making the changes to the PHP config file.

To fit in with the rest of DVWA, it would need to be in English. If you scripting is good enough, maybe offer a language option on it.

Submit a PR and I'll add comments to that.

**Comment by IamCarron** [comment]
Done, thanks for letting me contribute to the project

**Comment by digininja** [comment]
I've added a small warning to the readme, just because it is an external script, but I wouldn't have accepted it if I didn't think it was legit.

**Comment by IamCarron** [comment]
No problem! Thanks for letting me contribute to the project and helping me learn more about how to approach scripts.

**Comment by digininja** [comment]
I'm probably way overboard on cautious about the script, but I've had users
try to run Linux commands on Windows boxes so I know how bulletproof and
well documented things have to be.
