### ISSUE TITLE
Debian script install - MySQL 

### ISSUE THREAD

**Issue by aelharda** [digininja/DVWA#607]
Running the installation in Debian using the provided script in the repo, i'm unable to get past this stage as it keeps looping:

`Default credentials:
Username: root

Password: [No password just hit Enter]
Enter MySQL user: root
Enter MySQL password (press Enter for no password): 
Enter password: 

Error: Invalid MySQL credentials. Please check your username and password.

Default credentials:
Username: root

Password: [No password just hit Enter]
Enter MySQL user: 
`

**Comment by digininja** [comment]
> Note, this is not an official DVWA script, it was written by [IamCarron](https://github.com/iamCarron/). A lot of work went into creating the script and, when it was created, it did not do anything malicious, however it is recommended you review the script before blindly running it on your system, just in case. Please report any bugs to [IamCarron](https://github.com/iamCarron/), not here.

My guess would be though that you've set a MariaDB root password so the error is valid, you aren't entering the correct password.

**Comment by aelharda** [comment]
https://github.com/digininja/DVWA/assets/49875883/d2b5f793-f7fc-444d-8a5b-1413c8048e92

Clean install, no pwd set, please reference the above video recording

**Comment by digininja** [comment]
Please refer to the quote, it's not my problem.
