### ISSUE TITLE
My issue

### ISSUE THREAD

**Issue by cyber5kalki** [digininja/DVWA#608]
![image](https://github.com/digininja/DVWA/assets/136343742/b8d2eddd-c1e6-47f8-8cfd-9b79273d2836)

can any slove the issue im facing in using DWVA.

error is:-  Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'cyber_kalki'@'localhost' (using password: NO) in C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php:508 Stack trace: #0 C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php(508): mysqli_connect('127.0.0.1', 'cyber_kalki', Object(SensitiveParameterValue), '', '3306') #1 C:\xampp\htdocs\DVWA\login.php(8): dvwaDatabaseConnect() #2 {main} thrown in C:\xampp\htdocs\DVWA\dvwa\includes\dvwaPage.inc.php on line 508

**Comment by devwaqas126** [comment]
This issue is with your database connectivity. not bug in the app

**Comment by digininja** [comment]
The database credentials you've put in the config file are incorrect.

**Comment by cyber5kalki** [comment]
If possible, Can you send me the database file

**Comment by digininja** [comment]
Here you go, is isn't going to help you though, the problem is you've got the password wrong.

[dvwa_dump.sql.gz](https://github.com/digininja/DVWA/files/14021484/dvwa_dump.sql.gz)
