### ISSUE TITLE
DVWA ping not working

### ISSUE THREAD

**Issue by etmartian** [digininja/DVWA#613]
I am running Kali Live usb as pentest OS, then have a virtual box running Metasploitable 2.  Metasploitable 2 is up and running and logged in. My Firefox ESR browser is also open, and connected to DVWA.  I set the security of DVWA to low and attempted to go to command execution Web.  It says ping for free.  i type "ping 127.0.0.1" nothing happens.  I type "ping yahoo.com" nothing happens.  I tried lowering my security of browser but nothing can someone please help with this issue.

**Comment by digininja** [comment]
Where did you get the install of DVWA from? I only support the latest Github master branch.

**Comment by etmartian** [comment]
rapid 7. and also i downloaded chrome it is working fine there. thank you problem solved.  I seriously dont like google products though they are handy i believe its written purposely for mischevious reasons of snooping

**Comment by digininja** [comment]
Please close the ticket then.

And if you need support in the future, please install from this repo, not
from any other source.
