### ISSUE TITLE
When clicking on "Create / Reset Database" - only a blank page appears.

### ISSUE THREAD

**Issue by dragoshendu** [digininja/DVWA#616]
![2024-03-12_051839](https://github.com/digininja/DVWA/assets/162470383/592f2bdc-679e-48b7-9369-2e003df0e32d)

Hello.

Please help, I'm trying to install DVWA on Kali Linux on a virtualbox. When I click "Create/Reset Database" nothing appears but a blank page. And if I refresh this link again, I see the same form with “Create/Reset Database”.

**Comment by ShadowNinja89** [comment]
Could you please CAT out the last error in the Apache2 error log? The error log is at this location by default in Kali Linux distro: /var/log/apache2/error.log.

**Comment by ShadowNinja89** [comment]
In addition, you are seeing a blank screen instead of a PHP error messages because the Display_Error flag in PHP.Ini file is set to OFF as it defaults to OFF in production versions of PHP. It's helpful to turn this to On to force PHP to write errors to your browser.

**Comment by ShadowNinja89** [comment]
To help troubleshoot access errors with your database credentials, please also provide the output of the following MariaDB / MySQL SQL statements while logged in as the MariaDB root user:

1. SHOW grants FOR 'your MariaDB user login'@'localhost';
2. SELECT host, user, plugin FROM mysql.user;

**Comment by digininja** [comment]
Closing this due to not providing the information requested in the template.

Please work through the README for the install and if you still have problems create a new issue with the requested information.

**Comment by dragoshendu** [comment]
> Кроме того, вы видите пустой экран вместо сообщений об ошибках PHP, поскольку флаг Display_Error в файле PHP.Ini установлен в значение OFF, поскольку в производственных версиях PHP он по умолчанию отключен. Полезно включить этот параметр, чтобы заставить PHP записывать ошибки в ваш браузер. После этого перезапустите службу apache2. Если вы работаете от имени sudo (sudo su) в командной строке, введите: service apache2 restart и нажмите Enter, чтобы перезапустить службу Apache2.

Ok, I enabled Display_Error in the PHP.Ini file, this error appears when I click on "Create/Reset Database":

Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'user'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:13 Stack trace: #0 / var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php(13): mysqli_connect() #1 /var/www/html/dvwa/setup.php(23): include_once('...') #2 {main} thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 13

**Comment by digininja** [comment]
You've got the database credentials wrong. This ticket is closed, follow the README about how to set the database up and if you still have problems create a new ticket with the requested information.

**Comment by dragoshendu** [comment]
Why is it closed? I haven't solved the problem yet.

**Comment by digininja** [comment]
The issue template asks for specific information and says the issue will be closed if that information is not provided.

If you want support, create a new issue and provide the information requested.
