### ISSUE TITLE
Login page redirects to setup.php

### ISSUE THREAD

**Issue by herlit22** [digininja/DVWA#620]
Before you raise a bug, please make sure you have fully read the README, especially if your bug relates to configuring the database.

Issues will be closed if the answer is in the README and no obvious attempts have been made to follow it.

Support will only be given for users running the latest pull of code from GitHub. Not a tagged release, not a pre-installed app, not a ZIP you got from a mate.

**Describe the bug**
The setup.php page works. The program works, but fails to load properly(to an index.php i think) after login.php:
WHen I tried to log in to localhost/dvwa/login.php and put in admin/password, I log in successfully but the login.php page redirects
me to setup.php. It doesn't stay on login.php or goes to an index.php and shows all the tools/options to work with. It goes back to the setup.php config page and that's it.

**To Reproduce**
Install steps
git clone https://github.com/digininja/DVWA.git
mv DVWA dvwa
chmod -R 777 dvwa/
cd dvwa/config
cp config.inc.php.dist config.inc.php
set up user and pass for db
Set up this:
allow_url_fopen = On
allow_url_include = On
Created the dvwa database, did the grant and flushed privileges.
Apache + php already installed.

 IN the log you can see how it goes from login.php to setup.php

Steps to reproduce the behaviour:

**Logs**

127.0.0.1 - - [14/Mar/2024:14:53:03 -0400] "POST /dvwa/login.php HTTP/1.1" 302 476 "http://localhost/dvwa/login.php" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
127.0.0.1 - - [14/Mar/2024:14:53:03 -0400] "GET /dvwa/setup.php HTTP/1.1" 200 1902 "http://localhost/dvwa/login.php" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
**Expected behaviour**

**What have you done to help fix the issue yourself?**
What have you tried, what research have you done, what changes have you made.
I inspected the login.php source code but didn't find any redirects.
I installed again and got the same results.

**Screenshots**

**System (please complete the following information):**
 - OS: Kali
 - Database and Version [e.g. MySQL, MariaDB, 10.11.4-mariadb-1
 - PHP Version 8.2
apache 2.4.57 debian

**Comment by digininja** [comment]
Did you run the setup script from the setup page? Can you send the last few lines of the error log, that might help.

**Comment by herlit22** [comment]
This is the error.log. You'll see some authentication errors, but those were fixed when I created the dvwa db. Now that I watched your youtube video, I see that the redirect is correct(to setup.php) but the menu on the left only loads the three first items(Home, INstructions, reset db). 
I didn't try the script for the install. It's not installed on a container, but I'll try the script in an ubuntu machine this weekend.
Thanks a lot. 

APACHE ERRORS.LOG:

Thu Mar 14 13:47:32.538086 2024] [mpm_prefork:notice] [pid 7155] AH00163: Apache/2.4.57 (Debian) configured -- resuming normal operations
[Thu Mar 14 13:47:32.538225 2024] [core:notice] [pid 7155] AH00094: Command line: '/usr/sbin/apache2'
[Thu Mar 14 13:48:47.416056 2024] [php:error] [pid 7159] [client 192.168.0.247:44204] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 13:50:12.442255 2024] [php:error] [pid 7161] [client 192.168.0.94:54760] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 13:51:48.856463 2024] [php:error] [pid 7835] [client 192.168.0.247:45162] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 13:51:57.647174 2024] [php:error] [pid 7159] [client 192.168.0.247:53534] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 13:54:02.819625 2024] [php:error] [pid 7162] [client 192.168.0.247:50948] script '/var/www/html/index.php' not found or unable to stat
[Thu Mar 14 13:54:12.286277 2024] [php:error] [pid 7161] [client 192.168.0.247:43236] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 13:55:54.985607 2024] [php:error] [pid 7160] [client 192.168.0.94:57158] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 13:56:46.940078 2024] [php:error] [pid 7162] [client 127.0.0.1:44162] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 13:56:50.411209 2024] [php:error] [pid 7161] [client 127.0.0.1:44170] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:05:16.719115 2024] [php:error] [pid 12207] [client 127.0.0.1:40544] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:13:08.335775 2024] [php:error] [pid 7163] [client 127.0.0.1:50740] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:17:27.895123 2024] [php:error] [pid 12207] [client 127.0.0.1:48122] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:13\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php(13): mysqli_connect()\n#1 /var/www/html/dvwa/setup.php(23): include_once('...')\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 13, referer: http://localhost/dvwa/setup.php
[Thu Mar 14 14:17:37.856429 2024] [php:error] [pid 7159] [client 127.0.0.1:41384] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:21:18.574225 2024] [php:error] [pid 7161] [client 127.0.0.1:44998] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'admin'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:22:58.200151 2024] [php:error] [pid 12853] [client 127.0.0.1:32870] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user@127.0.0.1'@'%' to database 'dvwa' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:536\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(536): mysqli_query()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 536
[Thu Mar 14 14:22:59.267806 2024] [php:error] [pid 7835] [client 127.0.0.1:32884] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user@127.0.0.1'@'%' to database 'dvwa' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:536\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(536): mysqli_query()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 536
[Thu Mar 14 14:24:36.937052 2024] [mpm_prefork:notice] [pid 7155] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Mar 14 14:24:38.170498 2024] [mpm_prefork:notice] [pid 26533] AH00163: Apache/2.4.57 (Debian) configured -- resuming normal operations
[Thu Mar 14 14:24:38.170571 2024] [core:notice] [pid 26533] AH00094: Command line: '/usr/sbin/apache2'
[Thu Mar 14 14:25:02.458126 2024] [php:error] [pid 26545] [client 127.0.0.1:49776] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'%' to database 'dvwa' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:536\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(536): mysqli_query()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 536
[Thu Mar 14 14:25:03.524724 2024] [php:error] [pid 26547] [client 127.0.0.1:49786] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'%' to database 'dvwa' in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:536\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(536): mysqli_query()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 536
[Thu Mar 14 14:26:25.235944 2024] [php:error] [pid 26549] [client 127.0.0.1:58046] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'localhost' (using password: NO) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:26:26.426427 2024] [php:error] [pid 26548] [client 127.0.0.1:58048] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'user'@'localhost' (using password: NO) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:33:31.524325 2024] [php:error] [pid 26546] [client 127.0.0.1:33972] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:33:32.505942 2024] [php:error] [pid 26549] [client 127.0.0.1:33978] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:33:33.206460 2024] [php:error] [pid 26548] [client 127.0.0.1:33986] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwa'@'localhost' (using password: YES) in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:535\nStack trace:\n#0 /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php(535): mysqli_connect()\n#1 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 535
[Thu Mar 14 14:52:47.169365 2024] [mpm_prefork:notice] [pid 26533] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Mar 14 14:52:48.264277 2024] [mpm_prefork:notice] [pid 41774] AH00163: Apache/2.4.57 (Debian) configured -- resuming normal operations
[Thu Mar 14 14:52:48.264359 2024] [core:notice] [pid 41774] AH00094: Command line: '/usr/sbin/apache2'
[Thu Mar 14 15:57:05.469869 2024] [mpm_prefork:notice] [pid 8285] AH00163: Apache/2.4.57 (Debian) configured -- resuming normal operations
[Thu Mar 14 15:57:05.469951 2024] [core:notice] [pid 8285] AH00094: Command line: '/usr/sbin/apache2'

**Comment by digininja** [comment]
At the bottom of the setup page is a button to run the setup script, did
you click that?

**Comment by herlit22** [comment]
Problem solved. The database reset. I ran it a few times before but it didn't take. Now it's all working. :)
Thanks a lot
Best
Hernan

**Comment by digininja** [comment]
That has to be ran once before you can use the app as it creates the tables
and content.

Glad it's working, please now close the issue.
