### ISSUE TITLE
bkank page with http://127.0.0.1/dvwa/setup.php#

### ISSUE THREAD

**Issue by nguyenthanhdat27072004** [digininja/DVWA#621]
"Please help me fix DVWA. After completing all the steps and accessing http://127.0.0.1/dvwa/setup.php, when I choose 'create/reset database,' it shows a blank page with the URL http://127.0.0.1/dvwa/setup.php#. Could you please assist?"

**Comment by digininja** [comment]
Sounds like you've not set the database user up correctly but without all the extra information I request when you open this ticket I can't help further.

Please either provide the extra information or I'll have to close the ticket.

**Comment by nguyenthanhdat27072004** [comment]
How to set up a database user correctly. Please help me.
![Ảnh chụp màn hình 2024-04-02 205216](https://github.com/digininja/DVWA/assets/154571652/8ec18ae7-ff28-4c2d-ad01-0301d42ae183)

**Comment by digininja** [comment]
Please create a new ticket and follow the instructions in the ticket so you provide enough information.
