### ISSUE TITLE
"vulnerability" should be "vulnerabilities" on `index.php`

### ISSUE THREAD

**Issue by dnlwlsn** [digininja/DVWA#626]
"both documented and undocumented vulnerability" should be "both documented and undocumented vulnerabilities" in this context.

It's correct on `instructions.php` and `README.md`
![image](https://github.com/digininja/DVWA/assets/51659826/9ecec7fe-f385-4fad-896d-c5320bf6b88a)
![image](https://github.com/digininja/DVWA/assets/51659826/c2ca0bb9-3250-4910-8b70-6c2902999cef)

It's only incorrect on `index.php`
![image](https://github.com/digininja/DVWA/assets/51659826/5d57863d-1799-4395-b6d2-2266be466516)

**Comment by digininja** [comment]
Fixed it, thanks.
