### ISSUE TITLE
can't setup .. get error  

### ISSUE THREAD

**Issue by GreenAA** [digininja/DVWA#627]
![Screenshot 2024-05-02 222455](https://github.com/digininja/DVWA/assets/87846163/468a0581-a2a2-402b-838f-dd4d6f8f4993)
Questions here may or may not be answered depending on the state of the question, to increase your chance, read this before asking [Asking For Technical Help](https://digi.ninja/blog/asking_for_help.php).

Basically, the more details you give, the more chance of getting an answer. We need at least:

- Where did you get DVWA from? in >> hacklio
- What OS are you installing it on? win 11
[mysql_error.log](https://github.com/digininja/DVWA/files/15193065/mysql_error.log)

- Last five lines from the web server access and error log from the time the error occurred if you got that far.
- The error you got when you got stuck.
- Any previous errors.
- What you have tried to do yourself to fix the problem. (chang port , all what you say to cange in php file etc.. )

Support will only be given for users running the latest pull of code from GitHub. Not a tagged release, not a pre-installed app, not a ZIP you got from a mate.

**Comment by digininja** [comment]
I've no idea what hacklio is, but please try with the latest version of DVWA from this GitHub repo. 

A quick search for that error suggests it may be a local firewall issue. See what you have running and disable things if necessary. You can also check if it is listening by using the command line app to connect to the database using the credentials from the config file.

**Comment by digininja** [comment]
No response, closing
