### ISSUE TITLE
file inclusion error

### ISSUE THREAD

**Issue by cmq104** [digininja/DVWA#635]
Questions here may or may not be answered depending on the state of the question, to increase your chance, read this before asking [Asking For Technical Help](https://digi.ninja/blog/asking_for_help.php).

Basically, the more details you give, the more chance of getting an answer. We need at least:

- Where did you get DVWA from?
- github
- What OS are you installing it on?
- Ubuntu 18.04.6 LTS
- Last five lines from the web server access and error log from the time the error occurred if you got that far.
[-] Tested URL: http://localhost/DVWA/vulnerabilities/fi/?page=../../../../../../../etc/passwd (Not Vulnerable)
<br />
<b>Notice</b>:  Array to string conversion in <b>/var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php</b> on line <b>77</b><br />

- The error you got when you got stuck.
- 
![image](https://github.com/digininja/DVWA/assets/68173644/3f3c0f70-610a-4631-b831-b76be22f4454)

I write a python script to detect path travelsal vulnerabilities ,and it report Array to string conversion error.

my setup is in following picture
![image](https://github.com/digininja/DVWA/assets/68173644/f77c4ab3-f5ab-46b0-82de-716bd9e2046f)

- Any previous errors.
- no.
- What you have tried to do yourself to fix the problem.
at first i use dotdotslash(another github project which can detect path travelsal), and it report Array to string conversion error.
Then i try to put payload in url, and it works.
![image](https://github.com/digininja/DVWA/assets/68173644/5b0920aa-95fc-408a-b03b-dbaef527751e)
then i wrote a python script using chatgpt, trying to found if its dotdotslash's problem， but it shows the same error,

Support will only be given for users running the latest pull of code from GitHub. Not a tagged release, not a pre-installed app, not a ZIP you got from a mate.

**Comment by digininja** [comment]
It looks like you aren't running the latest version of DVWA

This is line 77 along with context and that line is not going to throw the error you are seeing.

```
 70 
 71     session_set_cookie_params([
 72         'lifetime' => $maxlifetime,
 73         'path' => '/',
 74         'domain' => $domain,
 75         'secure' => $secure,
 76         'httponly' => $httponly,
 77         'samesite' => $samesite
 78     ]);
 79 
 80     session_start();
 81 
```

Get the latest version of the app from this repo and try again.

**Comment by cmq104** [comment]
I tried two ways to download latest version , one for downloading code zip , one for git clone ,
the following picture shows how i git clone
![image](https://github.com/digininja/DVWA/assets/68173644/da48d774-9b3d-4e8a-b9c6-b98c05abc335)
and then i copy it into apache2 and restart apache2
![image](https://github.com/digininja/DVWA/assets/68173644/2bf958d2-91ba-4e33-bd3c-395919504232)
but it shows the same error
![image](https://github.com/digininja/DVWA/assets/68173644/fe32395f-15d9-497c-8fa8-46bd39da2e66)
the following picture shows /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php
![image](https://github.com/digininja/DVWA/assets/68173644/96fd6fd7-7f45-4f4a-9372-d416c062e52d)

btw, i don't understand why it can report this error either :(
it seems there is no array to string in line 77

**Comment by digininja** [comment]
Let's just check that you are looking at the right file. Edit ` /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php` and insert three lines of empty comments at the top of the file.
If the report is coming from this file, then the error should move to line 80, if it stays at 77 then something else is going wrong.

**Comment by cmq104** [comment]
i insert four blank at the top
![6f73f8b00c8643c82ed5f4c8846e8db](https://github.com/digininja/DVWA/assets/68173644/adc5600e-0471-43c9-90dd-52f0bbc29afd)
and it shows in line 81 now
![36e8567a80c16b4482b10e7a12b04eb](https://github.com/digininja/DVWA/assets/68173644/ae3a1559-4b8a-4a07-a5ea-187b91ba9081)

**Comment by digininja** [comment]
Got it, I think you might be running a version of PHP earlier than 7.3, can you check.

The definition of `session_set_cookie_params` changed from taking individual parameters to being able to take an array with named parameters from 7.3:

<https://www.php.net/session_set_cookie_params>

Version 7.2 reached end of life in 2020 so I'll count this as an unsupported version and ask you to upgrade to a newer version of php.

**Comment by cmq104** [comment]
I see.
My linux is ubuntu18.04 and apt-get only supply php7.2
i'll upgrade my system to 20.04 and try again
anyway ,thank you very much for your answering

**Comment by digininja** [comment]
Problem solved.
