### ISSUE TITLE
DVWA-Kali  showing blank pages

### ISSUE THREAD

**Issue by lakunzy7** [digininja/DVWA#638]
I have setup DVWA (Apache 2 and PHP 8.2) on my  Kali,
I can successfully access the follow following links  http://127.0.0.1/dvwa/setup.php, http://127.0.0.1/dvwa/instructions.php

BUT, whenever i click on _**### Create / Reset Database**_ it will redirect me to http://127.0.0.1/dvwa/setup.php#  which is blank page. 

And also The following Directory cannot  be access on DVWA ( 127.0.0.1/dvwa/ ) showing blank page.
 dvwa/login.php
 dvwa/setup.php/#

**_Below is the attached images_**

![redirect me to php# instend of login page](https://github.com/digininja/DVWA/assets/47754154/3823f5d1-500c-4612-b1e6-2d44bbdebcba)
![reset](https://github.com/digininja/DVWA/assets/47754154/f7bcdc98-bf45-4234-9408-d31f5b70c27c)
![login](https://github.com/digininja/DVWA/assets/47754154/1cf718f1-ce93-42e9-86e8-151f9524a5e1)
**Screenshots**
    Attached.

**Comment by digininja** [comment]
I need the log files, they are the things that tell us what is going wrong.

It would also help if you turned on the two display error settings as tells you to do in the install instructions as that would give you an error on the screen rather than an blank screen.

https://github.com/digininja/DVWA?tab=readme-ov-file#php-configuration

My guess is you've got the database credentials wrong in some way. When you turn on the error displays, and when you look at the logs, read the errors and then go to the troubleshooting section, find the error that matches yours, and work through the steps to fix it.

https://github.com/digininja/DVWA?tab=readme-ov-file#troubleshooting

**Comment by digininja** [comment]
You are showing me a bunch of comments in the config file, have you actually turned them on?

As it appears you are using mod php you also need to restart Apache after making the changes. The setup page will tell you if you've got it right.

**Comment by lakunzy7** [comment]
Error Show bellow 


Fatal error: Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/DBMS/MySQL.php:13 Stack trace: #0 /var/www/html/DVWA/setup.php(23): include_once() #1 {main} thrown in /var/www/html/DVWA/dvwa/includes/DBMS/MySQL.php on line 13



![php error](https://github.com/digininja/DVWA/assets/47754154/34ca5c74-a80d-4621-8b54-7bf4f043566f)

**Comment by digininja** [comment]
So some self help here, Google that error and see what it means and how to
fix it.

It is a very common one and there are plenty of answers for it.

**Comment by lakunzy7** [comment]
I HAVE TRIED ALL THE SOLUTION ONLINE , BUT STILL UNABLE TO FIXED THE ERROR.

**Comment by digininja** [comment]
WHAT SOLUTION YOU TRIED, I'M NOT A MIND READER, AND NO NEED TO SHOUT.

Send some screenshots of you working through the section of the README that relates to this are and show that there are no errors from any of them.

**Comment by digininja** [comment]
Assuming you either fixed your own problem.

**Comment by NoobHacker836** [comment]
run 'sudo systemctl enable mariadb' . Your DB is not running.

**Comment by digininja** [comment]
Access denied means the database is running but it rejecting the
credentials used to try to log in to it.

**Comment by NoobHacker836** [comment]
damn my bad. I got a similar error because my DB was not running. So I thought maybe same issue with this guy.
