### ISSUE TITLE
DVWA System error - config file not found.

### ISSUE THREAD

**Issue by ggkkaa** [digininja/DVWA#651]
**Describe the bug**
Web application returns "DVWA System error - config file not found" when  I have changed config.inc.php.dist to config.inc.php

**To Reproduce**
Windows 11, on Burp Suite Community Version. Change config.inc.php.dist to config.inc.php

Steps to reproduce the behaviour:

1. Seup a dvwa server using XAMPP
2. Copy config.inc.php.dist to config.inc.php
3. Open site using Burp Suite Community Edition

**Logs**
Which log? Access, error, or PHP error? I will post the error one
[Thu Aug 22 00:24:48.452353 2024] [mpm_winnt:notice] [pid 30008:tid 404] AH00354: Child: Starting 150 worker threads.
[Thu Aug 22 00:33:00.734277 2024] [core:error] [pid 30008:tid 1932] (20024)The given path is misformatted or contained invalid characters: [client 127.0.0.1:61094] AH00127: Cannot map GET /DVWA:3306 HTTP/1.1 to file
[Thu Aug 22 00:33:04.489476 2024] [core:error] [pid 30008:tid 1932] (20024)The given path is misformatted or contained invalid characters: [client 127.0.0.1:61094] AH00127: Cannot map GET /DVWA:3306 HTTP/1.1 to file
[Thu Aug 22 00:33:05.108606 2024] [core:error] [pid 30008:tid 1932] (20024)The given path is misformatted or contained invalid characters: [client 127.0.0.1:61094] AH00127: Cannot map GET /DVWA:3306 HTTP/1.1 to file
[Thu Aug 22 00:33:05.366687 2024] [core:error] [pid 30008:tid 1932] (20024)The given path is misformatted or contained invalid characters: [client 127.0.0.1:61094] AH00127: Cannot map GET /DVWA:3306 HTTP/1.1 to file

**Expected behaviour**
The site to open and work as usually

**What have you done to help fix the issue yourself?**
I have changed the config and tried to look at a closed issue about this error.

**Screenshots**
![image](https://github.com/user-attachments/assets/12cdfd75-166e-4765-9677-159965295428)
![image](https://github.com/user-attachments/assets/16b03339-435a-4a09-be7f-44fde6b28438)

**System (please complete the following information):**
 - OS: Windows 11
 - Database and Version: 10.4.32-MariaDB
 - PHP Version: PHP/8.2.12

**Comment by digininja** [comment]
I can't see your images as they are private. 

Can you show a command line directory listing of the config directory to prove the file is there.

Looking at the log, why are you trying to access the site on port 3306?

**Comment by ggkkaa** [comment]
It is there, int my image, but OK I will show a command line directory. Id on't know, It's set up that way, I just went on my server andaccesed it as localhost/dvwa. 

cmd listing:

PS C:\xampp\DVWA\config> Tree /F /A
Folder PATH listing for volume OS
Volume serial number is 2C23-00AC
C:.
    config.inc.php
    config.inc.php.dist

No subfolders exist

**Comment by digininja** [comment]
Send a screenshot of you trying to browse to DVWA and the last 10 lines in the access and error logs while trying to do it.

I have a feeling your document root is pointing to a different location.
