### ISSUE TITLE
After installing and configuring DVWA - The web app doesn't launch - Just shows a blank screen.

### ISSUE THREAD

**Issue by jeffreykeyes** [digininja/DVWA#653]
Hello Guys! 

I followed the instructions and configured mysql and the DVWA. 

mysql is in running state. However, when i launch the webapp (127.0.0.1/DVWA) it leads me to a white blank page.

**Comment by jeffreykeyes** [comment]
Currently running on 8.2

**Comment by digininja** [comment]
Please close this issue then create a new one filling in the template. In
doing that you'll give me the information I need to help you.

With what you've given so far I don't even know if you are in Windows,
Linux, or something else.

**Comment by digininja** [comment]
Closing due to insufficient information
