### ISSUE TITLE
rename file compose

### ISSUE THREAD

**Issue by ljamel** [digininja/DVWA#655]
Please rename file compose.yml in docker-compose.yml

~/DVWA$ docker-compose up -d .
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by digininja** [comment]
You are running an old version of the docker, `compose.yaml` or `compose.yml` is the current preferred name.

https://docs.docker.com/compose/intro/compose-application-model/
